(function(e, a) { for(var i in a) e[i] = a[i]; }(exports, /******/ (function(modules) { // webpackBootstrap
/******/ 	// The module cache
/******/ 	var installedModules = {};
/******/
/******/ 	// The require function
/******/ 	function __webpack_require__(moduleId) {
/******/
/******/ 		// Check if module is in cache
/******/ 		if(installedModules[moduleId]) {
/******/ 			return installedModules[moduleId].exports;
/******/ 		}
/******/ 		// Create a new module (and put it into the cache)
/******/ 		var module = installedModules[moduleId] = {
/******/ 			i: moduleId,
/******/ 			l: false,
/******/ 			exports: {}
/******/ 		};
/******/
/******/ 		// Execute the module function
/******/ 		modules[moduleId].call(module.exports, module, module.exports, __webpack_require__);
/******/
/******/ 		// Flag the module as loaded
/******/ 		module.l = true;
/******/
/******/ 		// Return the exports of the module
/******/ 		return module.exports;
/******/ 	}
/******/
/******/
/******/ 	// expose the modules object (__webpack_modules__)
/******/ 	__webpack_require__.m = modules;
/******/
/******/ 	// expose the module cache
/******/ 	__webpack_require__.c = installedModules;
/******/
/******/ 	// define getter function for harmony exports
/******/ 	__webpack_require__.d = function(exports, name, getter) {
/******/ 		if(!__webpack_require__.o(exports, name)) {
/******/ 			Object.defineProperty(exports, name, { enumerable: true, get: getter });
/******/ 		}
/******/ 	};
/******/
/******/ 	// define __esModule on exports
/******/ 	__webpack_require__.r = function(exports) {
/******/ 		if(typeof Symbol !== 'undefined' && Symbol.toStringTag) {
/******/ 			Object.defineProperty(exports, Symbol.toStringTag, { value: 'Module' });
/******/ 		}
/******/ 		Object.defineProperty(exports, '__esModule', { value: true });
/******/ 	};
/******/
/******/ 	// create a fake namespace object
/******/ 	// mode & 1: value is a module id, require it
/******/ 	// mode & 2: merge all properties of value into the ns
/******/ 	// mode & 4: return value when already ns object
/******/ 	// mode & 8|1: behave like require
/******/ 	__webpack_require__.t = function(value, mode) {
/******/ 		if(mode & 1) value = __webpack_require__(value);
/******/ 		if(mode & 8) return value;
/******/ 		if((mode & 4) && typeof value === 'object' && value && value.__esModule) return value;
/******/ 		var ns = Object.create(null);
/******/ 		__webpack_require__.r(ns);
/******/ 		Object.defineProperty(ns, 'default', { enumerable: true, value: value });
/******/ 		if(mode & 2 && typeof value != 'string') for(var key in value) __webpack_require__.d(ns, key, function(key) { return value[key]; }.bind(null, key));
/******/ 		return ns;
/******/ 	};
/******/
/******/ 	// getDefaultExport function for compatibility with non-harmony modules
/******/ 	__webpack_require__.n = function(module) {
/******/ 		var getter = module && module.__esModule ?
/******/ 			function getDefault() { return module['default']; } :
/******/ 			function getModuleExports() { return module; };
/******/ 		__webpack_require__.d(getter, 'a', getter);
/******/ 		return getter;
/******/ 	};
/******/
/******/ 	// Object.prototype.hasOwnProperty.call
/******/ 	__webpack_require__.o = function(object, property) { return Object.prototype.hasOwnProperty.call(object, property); };
/******/
/******/ 	// __webpack_public_path__
/******/ 	__webpack_require__.p = "";
/******/
/******/
/******/ 	// Load entry module and return exports
/******/ 	return __webpack_require__(__webpack_require__.s = 0);
/******/ })
/************************************************************************/
/******/ ({

/***/ "./node_modules/@angular/router/router.ngfactory.js":
/*!**********************************************************!*\
  !*** ./node_modules/@angular/router/router.ngfactory.js ***!
  \**********************************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
Object.defineProperty(exports, "__esModule", { value: true });
const i0 = __webpack_require__(/*! @angular/core */ "@angular/core");
const i1 = __webpack_require__(/*! @angular/router */ "@angular/router");
var RouterModuleNgFactory = i0.ɵcmf(i1.RouterModule, [], function (_l) { return i0.ɵmod([i0.ɵmpd(512, i0.ComponentFactoryResolver, i0.ɵCodegenComponentFactoryResolver, [[8, [ɵangular_packages_router_router_lNgFactory]], [3, i0.ComponentFactoryResolver], i0.NgModuleRef]), i0.ɵmpd(1073742336, i1.RouterModule, i1.RouterModule, [[2, i1.ɵangular_packages_router_router_a], [2, i1.Router]])]); });
exports.RouterModuleNgFactory = RouterModuleNgFactory;
var styles_ɵangular_packages_router_router_l = [];
var RenderType_ɵangular_packages_router_router_l = i0.ɵcrt({ encapsulation: 2, styles: styles_ɵangular_packages_router_router_l, data: {} });
exports.RenderType_ɵangular_packages_router_router_l = RenderType_ɵangular_packages_router_router_l;
function View_ɵangular_packages_router_router_l_0(_l) { return i0.ɵvid(0, [(_l()(), i0.ɵeld(0, 16777216, null, null, 1, "router-outlet", [], null, null, null, null, null)), i0.ɵdid(1, 212992, null, 0, i1.RouterOutlet, [i1.ChildrenOutletContexts, i0.ViewContainerRef, i0.ComponentFactoryResolver, [8, null], i0.ChangeDetectorRef], null, null)], function (_ck, _v) { _ck(_v, 1, 0); }, null); }
exports.View_ɵangular_packages_router_router_l_0 = View_ɵangular_packages_router_router_l_0;
function View_ɵangular_packages_router_router_l_Host_0(_l) { return i0.ɵvid(0, [(_l()(), i0.ɵeld(0, 0, null, null, 1, "ng-component", [], null, null, null, View_ɵangular_packages_router_router_l_0, RenderType_ɵangular_packages_router_router_l)), i0.ɵdid(1, 49152, null, 0, i1.ɵangular_packages_router_router_l, [], null, null)], null, null); }
exports.View_ɵangular_packages_router_router_l_Host_0 = View_ɵangular_packages_router_router_l_Host_0;
var ɵangular_packages_router_router_lNgFactory = i0.ɵccf("ng-component", i1.ɵangular_packages_router_router_l, View_ɵangular_packages_router_router_l_Host_0, {}, {}, []);
exports.ɵangular_packages_router_router_lNgFactory = ɵangular_packages_router_router_lNgFactory;


/***/ }),

/***/ "./src/app/app-routing.module.ts":
/*!***************************************!*\
  !*** ./src/app/app-routing.module.ts ***!
  \***************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

Object.defineProperty(exports, "__esModule", { value: true });
const router_1 = __webpack_require__(/*! @angular/router */ "@angular/router");
const ɵ0 = () => Promise.resolve().then(() => __webpack_require__(/*! ./modules/auth/auth.module.ngfactory */ "./src/app/modules/auth/auth.module.ngfactory.js")).then(m => m.AuthModuleNgFactory), ɵ1 = () => Promise.resolve().then(() => __webpack_require__(/*! ./modules/busses/busses.module.ngfactory */ "./src/app/modules/busses/busses.module.ngfactory.js")).then(m => m.BussesModuleNgFactory);
exports.ɵ0 = ɵ0;
exports.ɵ1 = ɵ1;
const routes = [
    {
        path: "",
        loadChildren: ɵ0
    },
    {
        path: "busses",
        loadChildren: ɵ1
    }
];
class AppRoutingModule {
}
exports.AppRoutingModule = AppRoutingModule;


/***/ }),

/***/ "./src/app/app.component.ngfactory.js":
/*!********************************************!*\
  !*** ./src/app/app.component.ngfactory.js ***!
  \********************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
Object.defineProperty(exports, "__esModule", { value: true });
const i0 = __webpack_require__(/*! ./app.component.scss.shim.ngstyle */ "./src/app/app.component.scss.shim.ngstyle.js");
const i1 = __webpack_require__(/*! @angular/core */ "@angular/core");
const i2 = __webpack_require__(/*! @angular/router */ "@angular/router");
const i3 = __webpack_require__(/*! ./app.component */ "./src/app/app.component.ts");
var styles_AppComponent = [i0.styles];
var RenderType_AppComponent = i1.ɵcrt({ encapsulation: 0, styles: styles_AppComponent, data: {} });
exports.RenderType_AppComponent = RenderType_AppComponent;
function View_AppComponent_0(_l) { return i1.ɵvid(0, [(_l()(), i1.ɵeld(0, 16777216, null, null, 1, "router-outlet", [], null, null, null, null, null)), i1.ɵdid(1, 212992, null, 0, i2.RouterOutlet, [i2.ChildrenOutletContexts, i1.ViewContainerRef, i1.ComponentFactoryResolver, [8, null], i1.ChangeDetectorRef], null, null)], function (_ck, _v) { _ck(_v, 1, 0); }, null); }
exports.View_AppComponent_0 = View_AppComponent_0;
function View_AppComponent_Host_0(_l) { return i1.ɵvid(0, [(_l()(), i1.ɵeld(0, 0, null, null, 1, "app-root", [], null, null, null, View_AppComponent_0, RenderType_AppComponent)), i1.ɵdid(1, 49152, null, 0, i3.AppComponent, [], null, null)], null, null); }
exports.View_AppComponent_Host_0 = View_AppComponent_Host_0;
var AppComponentNgFactory = i1.ɵccf("app-root", i3.AppComponent, View_AppComponent_Host_0, {}, {}, []);
exports.AppComponentNgFactory = AppComponentNgFactory;


/***/ }),

/***/ "./src/app/app.component.scss.shim.ngstyle.js":
/*!****************************************************!*\
  !*** ./src/app/app.component.scss.shim.ngstyle.js ***!
  \****************************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
Object.defineProperty(exports, "__esModule", { value: true });
var styles = ["\n/*# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IiIsImZpbGUiOiJzcmMvYXBwL2FwcC5jb21wb25lbnQuc2NzcyJ9 */"];
exports.styles = styles;


/***/ }),

/***/ "./src/app/app.component.ts":
/*!**********************************!*\
  !*** ./src/app/app.component.ts ***!
  \**********************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

Object.defineProperty(exports, "__esModule", { value: true });
class AppComponent {
    constructor() {
        this.title = 'busses';
    }
}
exports.AppComponent = AppComponent;


/***/ }),

/***/ "./src/app/app.module.ts":
/*!*******************************!*\
  !*** ./src/app/app.module.ts ***!
  \*******************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

Object.defineProperty(exports, "__esModule", { value: true });
class AppModule {
}
exports.AppModule = AppModule;


/***/ }),

/***/ "./src/app/app.server.module.ngfactory.js":
/*!************************************************!*\
  !*** ./src/app/app.server.module.ngfactory.js ***!
  \************************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
Object.defineProperty(exports, "__esModule", { value: true });
const i0 = __webpack_require__(/*! @angular/core */ "@angular/core");
const i1 = __webpack_require__(/*! ./app.server.module */ "./src/app/app.server.module.ts");
const i2 = __webpack_require__(/*! ./app.component */ "./src/app/app.component.ts");
const i3 = __webpack_require__(/*! ../../node_modules/@angular/router/router.ngfactory */ "./node_modules/@angular/router/router.ngfactory.js");
const i4 = __webpack_require__(/*! ./app.component.ngfactory */ "./src/app/app.component.ngfactory.js");
const i5 = __webpack_require__(/*! @angular/common */ "@angular/common");
const i6 = __webpack_require__(/*! @angular/platform-browser */ "@angular/platform-browser");
const i7 = __webpack_require__(/*! @angular/platform-server */ "@angular/platform-server");
const i8 = __webpack_require__(/*! @angular/animations/browser */ "@angular/animations/browser");
const i9 = __webpack_require__(/*! @angular/platform-browser/animations */ "@angular/platform-browser/animations");
const i10 = __webpack_require__(/*! @angular/router */ "@angular/router");
const i11 = __webpack_require__(/*! @angular/common/http */ "@angular/common/http");
const i12 = __webpack_require__(/*! ./modules/shared/services/storage.service */ "./src/app/modules/shared/services/storage.service.ts");
const i13 = __webpack_require__(/*! ./modules/shared/interceptors/jwt.interceptor */ "./src/app/modules/shared/interceptors/jwt.interceptor.ts");
const i14 = __webpack_require__(/*! @angular/forms */ "@angular/forms");
const i15 = __webpack_require__(/*! ./modules/shared/guards/auth.guard */ "./src/app/modules/shared/guards/auth.guard.ts");
const i16 = __webpack_require__(/*! ./modules/shared/guards/unauth.guard */ "./src/app/modules/shared/guards/unauth.guard.ts");
const i17 = __webpack_require__(/*! ./modules/shared/config/constants.config */ "./src/app/modules/shared/config/constants.config.ts");
const i18 = __webpack_require__(/*! @angular/animations */ "@angular/animations");
const i19 = __webpack_require__(/*! @nguniversal/module-map-ngfactory-loader */ "@nguniversal/module-map-ngfactory-loader");
const i20 = __webpack_require__(/*! ./app-routing.module */ "./src/app/app-routing.module.ts");
const i21 = __webpack_require__(/*! ./modules/shared/shared.module */ "./src/app/modules/shared/shared.module.ts");
const i22 = __webpack_require__(/*! ./app.module */ "./src/app/app.module.ts");
var AppServerModuleNgFactory = i0.ɵcmf(i1.AppServerModule, [i2.AppComponent], function (_l) { return i0.ɵmod([i0.ɵmpd(512, i0.ComponentFactoryResolver, i0.ɵCodegenComponentFactoryResolver, [[8, [i3.ɵangular_packages_router_router_lNgFactory, i4.AppComponentNgFactory]], [3, i0.ComponentFactoryResolver], i0.NgModuleRef]), i0.ɵmpd(5120, i0.LOCALE_ID, i0.ɵangular_packages_core_core_p, [[3, i0.LOCALE_ID]]), i0.ɵmpd(4608, i5.NgLocalization, i5.NgLocaleLocalization, [i0.LOCALE_ID, [2, i5.ɵangular_packages_common_common_a]]), i0.ɵmpd(5120, i0.ɵangular_packages_core_core_ba, i0.ɵangular_packages_core_core_r, [i0.NgZone]), i0.ɵmpd(5120, i0.IterableDiffers, i0.ɵangular_packages_core_core_n, []), i0.ɵmpd(5120, i0.KeyValueDiffers, i0.ɵangular_packages_core_core_o, []), i0.ɵmpd(4608, i6.DomSanitizer, i6.ɵDomSanitizerImpl, [i5.DOCUMENT]), i0.ɵmpd(6144, i0.Sanitizer, null, [i6.DomSanitizer]), i0.ɵmpd(4608, i6.HAMMER_GESTURE_CONFIG, i6.HammerGestureConfig, []), i0.ɵmpd(5120, i6.EVENT_MANAGER_PLUGINS, function (p0_0, p0_1, p0_2, p1_0, p2_0, p2_1, p2_2, p2_3, p3_0) { return [new i6.ɵDomEventsPlugin(p0_0, p0_1, p0_2), new i6.ɵKeyEventsPlugin(p1_0), new i6.ɵHammerGesturesPlugin(p2_0, p2_1, p2_2, p2_3), new i7.ɵangular_packages_platform_server_platform_server_d(p3_0)]; }, [i5.DOCUMENT, i0.NgZone, i0.PLATFORM_ID, i5.DOCUMENT, i5.DOCUMENT, i6.HAMMER_GESTURE_CONFIG, i0.ɵConsole, [2, i6.HAMMER_LOADER], i5.DOCUMENT]), i0.ɵmpd(4608, i6.EventManager, i6.EventManager, [i6.EVENT_MANAGER_PLUGINS, i0.NgZone]), i0.ɵmpd(135680, i6.ɵDomSharedStylesHost, i6.ɵDomSharedStylesHost, [i5.DOCUMENT]), i0.ɵmpd(4608, i6.ɵDomRendererFactory2, i6.ɵDomRendererFactory2, [i6.EventManager, i6.ɵDomSharedStylesHost, i0.APP_ID]), i0.ɵmpd(4608, i7.ɵangular_packages_platform_server_platform_server_c, i7.ɵangular_packages_platform_server_platform_server_c, [i5.DOCUMENT, [2, i6.ɵTRANSITION_ID]]), i0.ɵmpd(6144, i6.ɵSharedStylesHost, null, [i7.ɵangular_packages_platform_server_platform_server_c]), i0.ɵmpd(4608, i7.ɵServerRendererFactory2, i7.ɵServerRendererFactory2, [i6.EventManager, i0.NgZone, i5.DOCUMENT, i6.ɵSharedStylesHost]), i0.ɵmpd(4608, i8.AnimationDriver, i8.ɵNoopAnimationDriver, []), i0.ɵmpd(5120, i8.ɵAnimationStyleNormalizer, i9.ɵangular_packages_platform_browser_animations_animations_b, []), i0.ɵmpd(4608, i8.ɵAnimationEngine, i9.ɵInjectableAnimationEngine, [i5.DOCUMENT, i8.AnimationDriver, i8.ɵAnimationStyleNormalizer]), i0.ɵmpd(5120, i0.RendererFactory2, i7.ɵangular_packages_platform_server_platform_server_a, [i7.ɵServerRendererFactory2, i8.ɵAnimationEngine, i0.NgZone]), i0.ɵmpd(4352, i0.Testability, null, []), i0.ɵmpd(5120, i10.ActivatedRoute, i10.ɵangular_packages_router_router_g, [i10.Router]), i0.ɵmpd(4608, i10.NoPreloading, i10.NoPreloading, []), i0.ɵmpd(6144, i10.PreloadingStrategy, null, [i10.NoPreloading]), i0.ɵmpd(135680, i10.RouterPreloader, i10.RouterPreloader, [i10.Router, i0.NgModuleFactoryLoader, i0.Compiler, i0.Injector, i10.PreloadingStrategy]), i0.ɵmpd(4608, i10.PreloadAllModules, i10.PreloadAllModules, []), i0.ɵmpd(4608, i5.ViewportScroller, i5.ɵNullViewportScroller, []), i0.ɵmpd(5120, i10.ɵangular_packages_router_router_o, i10.ɵangular_packages_router_router_c, [i10.Router, i5.ViewportScroller, i10.ROUTER_CONFIGURATION]), i0.ɵmpd(5120, i10.ROUTER_INITIALIZER, i10.ɵangular_packages_router_router_j, [i10.ɵangular_packages_router_router_h]), i0.ɵmpd(5120, i0.APP_BOOTSTRAP_LISTENER, function (p0_0) { return [p0_0]; }, [i10.ROUTER_INITIALIZER]), i0.ɵmpd(4608, i11.HttpXsrfTokenExtractor, i11.ɵangular_packages_common_http_http_g, [i5.DOCUMENT, i0.PLATFORM_ID, i11.ɵangular_packages_common_http_http_e]), i0.ɵmpd(4608, i11.ɵangular_packages_common_http_http_h, i11.ɵangular_packages_common_http_http_h, [i11.HttpXsrfTokenExtractor, i11.ɵangular_packages_common_http_http_f]), i0.ɵmpd(4608, i12.StorageService, i12.StorageService, [i0.PLATFORM_ID]), i0.ɵmpd(5120, i11.HTTP_INTERCEPTORS, function (p0_0, p1_0) { return [p0_0, new i13.JwtInterceptor(p1_0)]; }, [i11.ɵangular_packages_common_http_http_h, i12.StorageService]), i0.ɵmpd(4608, i11.XhrFactory, i7.ɵangular_packages_platform_server_platform_server_e, []), i0.ɵmpd(4608, i11.HttpXhrBackend, i11.HttpXhrBackend, [i11.XhrFactory]), i0.ɵmpd(6144, i11.HttpBackend, null, [i11.HttpXhrBackend]), i0.ɵmpd(5120, i11.HttpHandler, i7.ɵangular_packages_platform_server_platform_server_f, [i11.HttpBackend, i0.Injector]), i0.ɵmpd(4608, i11.HttpClient, i11.HttpClient, [i11.HttpHandler]), i0.ɵmpd(4608, i11.ɵangular_packages_common_http_http_d, i11.ɵangular_packages_common_http_http_d, []), i0.ɵmpd(4608, i14.ɵangular_packages_forms_forms_o, i14.ɵangular_packages_forms_forms_o, []), i0.ɵmpd(4608, i14.FormBuilder, i14.FormBuilder, []), i0.ɵmpd(4608, i15.AuthGuard, i15.AuthGuard, [i10.Router, i12.StorageService]), i0.ɵmpd(4608, i16.UnauthGuard, i16.UnauthGuard, [i10.Router, i12.StorageService]), i0.ɵmpd(4608, i17.Constants, i17.Constants, []), i0.ɵmpd(4608, i18.AnimationBuilder, i9.ɵBrowserAnimationBuilder, [i0.RendererFactory2, i5.DOCUMENT]), i0.ɵmpd(4608, i6.TransferState, i6.TransferState, []), i0.ɵmpd(5120, i7.BEFORE_APP_SERIALIZED, function (p0_0, p0_1, p0_2) { return [i7.ɵangular_packages_platform_server_platform_server_b(p0_0, p0_1, p0_2)]; }, [i5.DOCUMENT, i0.APP_ID, i6.TransferState]), i0.ɵmpd(1073742336, i5.CommonModule, i5.CommonModule, []), i0.ɵmpd(1024, i0.ErrorHandler, i6.ɵangular_packages_platform_browser_platform_browser_a, []), i0.ɵmpd(1024, i0.NgProbeToken, function () { return [i10.ɵangular_packages_router_router_b()]; }, []), i0.ɵmpd(512, i10.ɵangular_packages_router_router_h, i10.ɵangular_packages_router_router_h, [i0.Injector]), i0.ɵmpd(256, i0.APP_ID, "busses", []), i0.ɵmpd(2048, i6.ɵTRANSITION_ID, null, [i0.APP_ID]), i0.ɵmpd(1024, i0.APP_INITIALIZER, function (p0_0, p1_0, p2_0, p2_1, p2_2) { return [i6.ɵangular_packages_platform_browser_platform_browser_j(p0_0), i10.ɵangular_packages_router_router_i(p1_0), i6.ɵangular_packages_platform_browser_platform_browser_h(p2_0, p2_1, p2_2)]; }, [[2, i0.NgProbeToken], i10.ɵangular_packages_router_router_h, i6.ɵTRANSITION_ID, i5.DOCUMENT, i0.Injector]), i0.ɵmpd(512, i0.ApplicationInitStatus, i0.ApplicationInitStatus, [[2, i0.APP_INITIALIZER]]), i0.ɵmpd(131584, i0.ApplicationRef, i0.ApplicationRef, [i0.NgZone, i0.ɵConsole, i0.Injector, i0.ErrorHandler, i0.ComponentFactoryResolver, i0.ApplicationInitStatus]), i0.ɵmpd(1073742336, i0.ApplicationModule, i0.ApplicationModule, [i0.ApplicationRef]), i0.ɵmpd(1073742336, i6.BrowserModule, i6.BrowserModule, [[3, i6.BrowserModule]]), i0.ɵmpd(1024, i10.ɵangular_packages_router_router_a, i10.ɵangular_packages_router_router_e, [[3, i10.Router]]), i0.ɵmpd(512, i10.UrlSerializer, i10.DefaultUrlSerializer, []), i0.ɵmpd(512, i10.ChildrenOutletContexts, i10.ChildrenOutletContexts, []), i0.ɵmpd(256, i10.ROUTER_CONFIGURATION, {}, []), i0.ɵmpd(1024, i5.LocationStrategy, i10.ɵangular_packages_router_router_d, [i5.PlatformLocation, [2, i5.APP_BASE_HREF], i10.ROUTER_CONFIGURATION]), i0.ɵmpd(512, i5.Location, i5.Location, [i5.LocationStrategy, i5.PlatformLocation]), i0.ɵmpd(512, i0.Compiler, i0.Compiler, []), i0.ɵmpd(512, i0.NgModuleFactoryLoader, i19.ModuleMapNgFactoryLoader, [i0.Compiler, i19.MODULE_MAP]), i0.ɵmpd(1024, i10.ROUTES, function () { return [[{ path: "", loadChildren: i20.ɵ0 }, { path: "busses", loadChildren: i20.ɵ1 }]]; }, []), i0.ɵmpd(1024, i10.Router, i10.ɵangular_packages_router_router_f, [i0.ApplicationRef, i10.UrlSerializer, i10.ChildrenOutletContexts, i5.Location, i0.Injector, i0.NgModuleFactoryLoader, i0.Compiler, i10.ROUTES, i10.ROUTER_CONFIGURATION, [2, i10.UrlHandlingStrategy], [2, i10.RouteReuseStrategy]]), i0.ɵmpd(1073742336, i10.RouterModule, i10.RouterModule, [[2, i10.ɵangular_packages_router_router_a], [2, i10.Router]]), i0.ɵmpd(1073742336, i20.AppRoutingModule, i20.AppRoutingModule, []), i0.ɵmpd(1073742336, i11.HttpClientXsrfModule, i11.HttpClientXsrfModule, []), i0.ɵmpd(1073742336, i11.HttpClientModule, i11.HttpClientModule, []), i0.ɵmpd(1073742336, i14.ɵangular_packages_forms_forms_d, i14.ɵangular_packages_forms_forms_d, []), i0.ɵmpd(1073742336, i14.FormsModule, i14.FormsModule, []), i0.ɵmpd(1073742336, i14.ReactiveFormsModule, i14.ReactiveFormsModule, []), i0.ɵmpd(1073742336, i21.SharedModule, i21.SharedModule, []), i0.ɵmpd(1073742336, i22.AppModule, i22.AppModule, []), i0.ɵmpd(1073742336, i9.NoopAnimationsModule, i9.NoopAnimationsModule, []), i0.ɵmpd(1073742336, i7.ServerModule, i7.ServerModule, []), i0.ɵmpd(1073742336, i7.ServerTransferStateModule, i7.ServerTransferStateModule, []), i0.ɵmpd(1073742336, i19.ModuleMapLoaderModule, i19.ModuleMapLoaderModule, []), i0.ɵmpd(1073742336, i1.AppServerModule, i1.AppServerModule, []), i0.ɵmpd(256, i0.ɵAPP_ROOT, true, []), i0.ɵmpd(256, i11.ɵangular_packages_common_http_http_e, "XSRF-TOKEN", []), i0.ɵmpd(256, i11.ɵangular_packages_common_http_http_f, "X-XSRF-TOKEN", []), i0.ɵmpd(256, i9.ANIMATION_MODULE_TYPE, "NoopAnimations", [])]); });
exports.AppServerModuleNgFactory = AppServerModuleNgFactory;


/***/ }),

/***/ "./src/app/app.server.module.ts":
/*!**************************************!*\
  !*** ./src/app/app.server.module.ts ***!
  \**************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

Object.defineProperty(exports, "__esModule", { value: true });
class AppServerModule {
}
exports.AppServerModule = AppServerModule;


/***/ }),

/***/ "./src/app/constants.ts":
/*!******************************!*\
  !*** ./src/app/constants.ts ***!
  \******************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

Object.defineProperty(exports, "__esModule", { value: true });
exports.JWT_KEY = 'JwtKey';


/***/ }),

/***/ "./src/app/modules/auth/auth.module.ngfactory.js":
/*!*******************************************************!*\
  !*** ./src/app/modules/auth/auth.module.ngfactory.js ***!
  \*******************************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
Object.defineProperty(exports, "__esModule", { value: true });
const i0 = __webpack_require__(/*! @angular/core */ "@angular/core");
const i1 = __webpack_require__(/*! ./auth.module */ "./src/app/modules/auth/auth.module.ts");
const i2 = __webpack_require__(/*! ../../../../node_modules/@angular/router/router.ngfactory */ "./node_modules/@angular/router/router.ngfactory.js");
const i3 = __webpack_require__(/*! ./components/login/login.component.ngfactory */ "./src/app/modules/auth/components/login/login.component.ngfactory.js");
const i4 = __webpack_require__(/*! ./components/register/register.component.ngfactory */ "./src/app/modules/auth/components/register/register.component.ngfactory.js");
const i5 = __webpack_require__(/*! @angular/common */ "@angular/common");
const i6 = __webpack_require__(/*! @angular/forms */ "@angular/forms");
const i7 = __webpack_require__(/*! ./services/auth.service */ "./src/app/modules/auth/services/auth.service.ts");
const i8 = __webpack_require__(/*! @angular/common/http */ "@angular/common/http");
const i9 = __webpack_require__(/*! ../shared/config/constants.config */ "./src/app/modules/shared/config/constants.config.ts");
const i10 = __webpack_require__(/*! ../shared/services/storage.service */ "./src/app/modules/shared/services/storage.service.ts");
const i11 = __webpack_require__(/*! @angular/router */ "@angular/router");
const i12 = __webpack_require__(/*! ../shared/shared.module */ "./src/app/modules/shared/shared.module.ts");
const i13 = __webpack_require__(/*! ./auth.routing.module */ "./src/app/modules/auth/auth.routing.module.ts");
const i14 = __webpack_require__(/*! ./components/login/login.component */ "./src/app/modules/auth/components/login/login.component.ts");
const i15 = __webpack_require__(/*! ../shared/guards/unauth.guard */ "./src/app/modules/shared/guards/unauth.guard.ts");
const i16 = __webpack_require__(/*! ./components/register/register.component */ "./src/app/modules/auth/components/register/register.component.ts");
var AuthModuleNgFactory = i0.ɵcmf(i1.AuthModule, [], function (_l) { return i0.ɵmod([i0.ɵmpd(512, i0.ComponentFactoryResolver, i0.ɵCodegenComponentFactoryResolver, [[8, [i2.ɵangular_packages_router_router_lNgFactory, i3.LoginComponentNgFactory, i4.RegisterComponentNgFactory]], [3, i0.ComponentFactoryResolver], i0.NgModuleRef]), i0.ɵmpd(4608, i5.NgLocalization, i5.NgLocaleLocalization, [i0.LOCALE_ID, [2, i5.ɵangular_packages_common_common_a]]), i0.ɵmpd(4608, i6.ɵangular_packages_forms_forms_o, i6.ɵangular_packages_forms_forms_o, []), i0.ɵmpd(4608, i6.FormBuilder, i6.FormBuilder, []), i0.ɵmpd(4608, i7.AuthService, i7.AuthService, [i8.HttpClient, i9.Constants, i10.StorageService]), i0.ɵmpd(1073742336, i5.CommonModule, i5.CommonModule, []), i0.ɵmpd(1073742336, i11.RouterModule, i11.RouterModule, [[2, i11.ɵangular_packages_router_router_a], [2, i11.Router]]), i0.ɵmpd(1073742336, i6.ɵangular_packages_forms_forms_d, i6.ɵangular_packages_forms_forms_d, []), i0.ɵmpd(1073742336, i6.FormsModule, i6.FormsModule, []), i0.ɵmpd(1073742336, i6.ReactiveFormsModule, i6.ReactiveFormsModule, []), i0.ɵmpd(1073742336, i12.SharedModule, i12.SharedModule, []), i0.ɵmpd(1073742336, i13.AuthRoutingModule, i13.AuthRoutingModule, []), i0.ɵmpd(1073742336, i1.AuthModule, i1.AuthModule, []), i0.ɵmpd(1024, i11.ROUTES, function () { return [[{ path: "", redirectTo: "login" }, { path: "login", component: i14.LoginComponent, canActivate: [i15.UnauthGuard] }, { path: "register", component: i16.RegisterComponent, canActivate: [i15.UnauthGuard] }]]; }, [])]); });
exports.AuthModuleNgFactory = AuthModuleNgFactory;


/***/ }),

/***/ "./src/app/modules/auth/auth.module.ts":
/*!*********************************************!*\
  !*** ./src/app/modules/auth/auth.module.ts ***!
  \*********************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

Object.defineProperty(exports, "__esModule", { value: true });
class AuthModule {
}
exports.AuthModule = AuthModule;


/***/ }),

/***/ "./src/app/modules/auth/auth.routing.module.ts":
/*!*****************************************************!*\
  !*** ./src/app/modules/auth/auth.routing.module.ts ***!
  \*****************************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

Object.defineProperty(exports, "__esModule", { value: true });
const router_1 = __webpack_require__(/*! @angular/router */ "@angular/router");
const login_component_1 = __webpack_require__(/*! ./components/login/login.component */ "./src/app/modules/auth/components/login/login.component.ts");
const register_component_1 = __webpack_require__(/*! ./components/register/register.component */ "./src/app/modules/auth/components/register/register.component.ts");
const unauth_guard_1 = __webpack_require__(/*! ../shared/guards/unauth.guard */ "./src/app/modules/shared/guards/unauth.guard.ts");
const routes = [
    {
        path: '',
        redirectTo: 'login'
    },
    {
        path: 'login',
        component: login_component_1.LoginComponent,
        canActivate: [unauth_guard_1.UnauthGuard]
    },
    {
        path: 'register',
        component: register_component_1.RegisterComponent,
        canActivate: [unauth_guard_1.UnauthGuard]
    }
];
class AuthRoutingModule {
}
exports.AuthRoutingModule = AuthRoutingModule;


/***/ }),

/***/ "./src/app/modules/auth/components/login/login.component.ngfactory.js":
/*!****************************************************************************!*\
  !*** ./src/app/modules/auth/components/login/login.component.ngfactory.js ***!
  \****************************************************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
Object.defineProperty(exports, "__esModule", { value: true });
const i0 = __webpack_require__(/*! ./login.component.scss.shim.ngstyle */ "./src/app/modules/auth/components/login/login.component.scss.shim.ngstyle.js");
const i1 = __webpack_require__(/*! @angular/core */ "@angular/core");
const i2 = __webpack_require__(/*! @angular/forms */ "@angular/forms");
const i3 = __webpack_require__(/*! @angular/router */ "@angular/router");
const i4 = __webpack_require__(/*! ./login.component */ "./src/app/modules/auth/components/login/login.component.ts");
const i5 = __webpack_require__(/*! ../../services/auth.service */ "./src/app/modules/auth/services/auth.service.ts");
var styles_LoginComponent = [i0.styles];
var RenderType_LoginComponent = i1.ɵcrt({ encapsulation: 0, styles: styles_LoginComponent, data: {} });
exports.RenderType_LoginComponent = RenderType_LoginComponent;
function View_LoginComponent_0(_l) { return i1.ɵvid(0, [(_l()(), i1.ɵeld(0, 0, null, null, 32, "div", [["class", "responsive-flex-wrapper"]], null, null, null, null, null)), (_l()(), i1.ɵeld(1, 0, null, null, 31, "div", [["class", "form-wrapper"]], null, null, null, null, null)), (_l()(), i1.ɵeld(2, 0, null, null, 1, "div", [["class", "form-title"]], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, ["Login"])), (_l()(), i1.ɵeld(4, 0, null, null, 28, "form", [["novalidate", ""]], [[2, "ng-untouched", null], [2, "ng-touched", null], [2, "ng-pristine", null], [2, "ng-dirty", null], [2, "ng-valid", null], [2, "ng-invalid", null], [2, "ng-pending", null]], [[null, "submit"], [null, "reset"]], function (_v, en, $event) { var ad = true; if (("submit" === en)) {
        var pd_0 = (i1.ɵnov(_v, 6).onSubmit($event) !== false);
        ad = (pd_0 && ad);
    } if (("reset" === en)) {
        var pd_1 = (i1.ɵnov(_v, 6).onReset() !== false);
        ad = (pd_1 && ad);
    } return ad; }, null, null)), i1.ɵdid(5, 16384, null, 0, i2.ɵangular_packages_forms_forms_z, [], null, null), i1.ɵdid(6, 540672, null, 0, i2.FormGroupDirective, [[8, null], [8, null]], { form: [0, "form"] }, null), i1.ɵprd(2048, null, i2.ControlContainer, null, [i2.FormGroupDirective]), i1.ɵdid(8, 16384, null, 0, i2.NgControlStatusGroup, [[4, i2.ControlContainer]], null, null), (_l()(), i1.ɵeld(9, 0, null, null, 8, "div", [["class", "form-group"]], null, null, null, null, null)), (_l()(), i1.ɵeld(10, 0, null, null, 1, "label", [["for", "login-email"]], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, ["Email address"])), (_l()(), i1.ɵeld(12, 0, null, null, 5, "input", [["class", "form-control"], ["formControlName", "email"], ["id", "login-email"], ["placeholder", "Email"], ["type", "email"]], [[2, "ng-untouched", null], [2, "ng-touched", null], [2, "ng-pristine", null], [2, "ng-dirty", null], [2, "ng-valid", null], [2, "ng-invalid", null], [2, "ng-pending", null]], [[null, "input"], [null, "blur"], [null, "compositionstart"], [null, "compositionend"]], function (_v, en, $event) { var ad = true; if (("input" === en)) {
        var pd_0 = (i1.ɵnov(_v, 13)._handleInput($event.target.value) !== false);
        ad = (pd_0 && ad);
    } if (("blur" === en)) {
        var pd_1 = (i1.ɵnov(_v, 13).onTouched() !== false);
        ad = (pd_1 && ad);
    } if (("compositionstart" === en)) {
        var pd_2 = (i1.ɵnov(_v, 13)._compositionStart() !== false);
        ad = (pd_2 && ad);
    } if (("compositionend" === en)) {
        var pd_3 = (i1.ɵnov(_v, 13)._compositionEnd($event.target.value) !== false);
        ad = (pd_3 && ad);
    } return ad; }, null, null)), i1.ɵdid(13, 16384, null, 0, i2.DefaultValueAccessor, [i1.Renderer2, i1.ElementRef, [2, i2.COMPOSITION_BUFFER_MODE]], null, null), i1.ɵprd(1024, null, i2.NG_VALUE_ACCESSOR, function (p0_0) { return [p0_0]; }, [i2.DefaultValueAccessor]), i1.ɵdid(15, 671744, null, 0, i2.FormControlName, [[3, i2.ControlContainer], [8, null], [8, null], [6, i2.NG_VALUE_ACCESSOR], [2, i2.ɵangular_packages_forms_forms_q]], { name: [0, "name"] }, null), i1.ɵprd(2048, null, i2.NgControl, null, [i2.FormControlName]), i1.ɵdid(17, 16384, null, 0, i2.NgControlStatus, [[4, i2.NgControl]], null, null), (_l()(), i1.ɵeld(18, 0, null, null, 8, "div", [["class", "form-group"]], null, null, null, null, null)), (_l()(), i1.ɵeld(19, 0, null, null, 1, "label", [["for", "login-password"]], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, ["Password"])), (_l()(), i1.ɵeld(21, 0, null, null, 5, "input", [["class", "form-control"], ["formControlName", "password"], ["id", "login-password"], ["placeholder", "Password"], ["type", "password"]], [[2, "ng-untouched", null], [2, "ng-touched", null], [2, "ng-pristine", null], [2, "ng-dirty", null], [2, "ng-valid", null], [2, "ng-invalid", null], [2, "ng-pending", null]], [[null, "input"], [null, "blur"], [null, "compositionstart"], [null, "compositionend"]], function (_v, en, $event) { var ad = true; if (("input" === en)) {
        var pd_0 = (i1.ɵnov(_v, 22)._handleInput($event.target.value) !== false);
        ad = (pd_0 && ad);
    } if (("blur" === en)) {
        var pd_1 = (i1.ɵnov(_v, 22).onTouched() !== false);
        ad = (pd_1 && ad);
    } if (("compositionstart" === en)) {
        var pd_2 = (i1.ɵnov(_v, 22)._compositionStart() !== false);
        ad = (pd_2 && ad);
    } if (("compositionend" === en)) {
        var pd_3 = (i1.ɵnov(_v, 22)._compositionEnd($event.target.value) !== false);
        ad = (pd_3 && ad);
    } return ad; }, null, null)), i1.ɵdid(22, 16384, null, 0, i2.DefaultValueAccessor, [i1.Renderer2, i1.ElementRef, [2, i2.COMPOSITION_BUFFER_MODE]], null, null), i1.ɵprd(1024, null, i2.NG_VALUE_ACCESSOR, function (p0_0) { return [p0_0]; }, [i2.DefaultValueAccessor]), i1.ɵdid(24, 671744, null, 0, i2.FormControlName, [[3, i2.ControlContainer], [8, null], [8, null], [6, i2.NG_VALUE_ACCESSOR], [2, i2.ɵangular_packages_forms_forms_q]], { name: [0, "name"] }, null), i1.ɵprd(2048, null, i2.NgControl, null, [i2.FormControlName]), i1.ɵdid(26, 16384, null, 0, i2.NgControlStatus, [[4, i2.NgControl]], null, null), (_l()(), i1.ɵeld(27, 0, null, null, 1, "button", [["class", "btn btn-primary float-right"]], [[8, "disabled", 0]], [[null, "click"]], function (_v, en, $event) { var ad = true; var _co = _v.component; if (("click" === en)) {
        var pd_0 = (_co.onLogin() !== false);
        ad = (pd_0 && ad);
    } return ad; }, null, null)), (_l()(), i1.ɵted(-1, null, ["Login"])), (_l()(), i1.ɵeld(29, 0, null, null, 3, "button", [["class", "btn btn-success float-right mr-2"]], null, [[null, "click"]], function (_v, en, $event) { var ad = true; if (("click" === en)) {
        var pd_0 = (i1.ɵnov(_v, 30).onClick() !== false);
        ad = (pd_0 && ad);
    } return ad; }, null, null)), i1.ɵdid(30, 16384, null, 0, i3.RouterLink, [i3.Router, i3.ActivatedRoute, [8, null], i1.Renderer2, i1.ElementRef], { routerLink: [0, "routerLink"] }, null), i1.ɵpad(31, 1), (_l()(), i1.ɵted(-1, null, ["Register"]))], function (_ck, _v) { var _co = _v.component; var currVal_7 = _co.loginForm; _ck(_v, 6, 0, currVal_7); var currVal_15 = "email"; _ck(_v, 15, 0, currVal_15); var currVal_23 = "password"; _ck(_v, 24, 0, currVal_23); var currVal_25 = _ck(_v, 31, 0, "/register"); _ck(_v, 30, 0, currVal_25); }, function (_ck, _v) { var _co = _v.component; var currVal_0 = i1.ɵnov(_v, 8).ngClassUntouched; var currVal_1 = i1.ɵnov(_v, 8).ngClassTouched; var currVal_2 = i1.ɵnov(_v, 8).ngClassPristine; var currVal_3 = i1.ɵnov(_v, 8).ngClassDirty; var currVal_4 = i1.ɵnov(_v, 8).ngClassValid; var currVal_5 = i1.ɵnov(_v, 8).ngClassInvalid; var currVal_6 = i1.ɵnov(_v, 8).ngClassPending; _ck(_v, 4, 0, currVal_0, currVal_1, currVal_2, currVal_3, currVal_4, currVal_5, currVal_6); var currVal_8 = i1.ɵnov(_v, 17).ngClassUntouched; var currVal_9 = i1.ɵnov(_v, 17).ngClassTouched; var currVal_10 = i1.ɵnov(_v, 17).ngClassPristine; var currVal_11 = i1.ɵnov(_v, 17).ngClassDirty; var currVal_12 = i1.ɵnov(_v, 17).ngClassValid; var currVal_13 = i1.ɵnov(_v, 17).ngClassInvalid; var currVal_14 = i1.ɵnov(_v, 17).ngClassPending; _ck(_v, 12, 0, currVal_8, currVal_9, currVal_10, currVal_11, currVal_12, currVal_13, currVal_14); var currVal_16 = i1.ɵnov(_v, 26).ngClassUntouched; var currVal_17 = i1.ɵnov(_v, 26).ngClassTouched; var currVal_18 = i1.ɵnov(_v, 26).ngClassPristine; var currVal_19 = i1.ɵnov(_v, 26).ngClassDirty; var currVal_20 = i1.ɵnov(_v, 26).ngClassValid; var currVal_21 = i1.ɵnov(_v, 26).ngClassInvalid; var currVal_22 = i1.ɵnov(_v, 26).ngClassPending; _ck(_v, 21, 0, currVal_16, currVal_17, currVal_18, currVal_19, currVal_20, currVal_21, currVal_22); var currVal_24 = !_co.loginForm.valid; _ck(_v, 27, 0, currVal_24); }); }
exports.View_LoginComponent_0 = View_LoginComponent_0;
function View_LoginComponent_Host_0(_l) { return i1.ɵvid(0, [(_l()(), i1.ɵeld(0, 0, null, null, 1, "app-login", [], null, null, null, View_LoginComponent_0, RenderType_LoginComponent)), i1.ɵdid(1, 114688, null, 0, i4.LoginComponent, [i5.AuthService, i3.Router], null, null)], function (_ck, _v) { _ck(_v, 1, 0); }, null); }
exports.View_LoginComponent_Host_0 = View_LoginComponent_Host_0;
var LoginComponentNgFactory = i1.ɵccf("app-login", i4.LoginComponent, View_LoginComponent_Host_0, {}, {}, []);
exports.LoginComponentNgFactory = LoginComponentNgFactory;


/***/ }),

/***/ "./src/app/modules/auth/components/login/login.component.scss.shim.ngstyle.js":
/*!************************************************************************************!*\
  !*** ./src/app/modules/auth/components/login/login.component.scss.shim.ngstyle.js ***!
  \************************************************************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
Object.defineProperty(exports, "__esModule", { value: true });
var styles = ["\n/*# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IiIsImZpbGUiOiJzcmMvYXBwL21vZHVsZXMvYXV0aC9jb21wb25lbnRzL2xvZ2luL2xvZ2luLmNvbXBvbmVudC5zY3NzIn0= */"];
exports.styles = styles;


/***/ }),

/***/ "./src/app/modules/auth/components/login/login.component.ts":
/*!******************************************************************!*\
  !*** ./src/app/modules/auth/components/login/login.component.ts ***!
  \******************************************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

Object.defineProperty(exports, "__esModule", { value: true });
const core_1 = __webpack_require__(/*! @angular/core */ "@angular/core");
const forms_1 = __webpack_require__(/*! @angular/forms */ "@angular/forms");
class LoginComponent {
    constructor(authService, router) {
        this.authService = authService;
        this.router = router;
        this.loginForm = new forms_1.FormGroup({
            email: new forms_1.FormControl('', [forms_1.Validators.required, forms_1.Validators.email]),
            password: new forms_1.FormControl('', [forms_1.Validators.required])
        });
    }
    ngOnInit() { }
    onLogin() {
        const email = this.loginForm.controls['email'].value;
        const password = this.loginForm.controls['password'].value;
        this.authService.login(email, password)
            .subscribe(() => {
            this.router.navigate(['/busses']);
        });
    }
}
exports.LoginComponent = LoginComponent;


/***/ }),

/***/ "./src/app/modules/auth/components/register/register.component.ngfactory.js":
/*!**********************************************************************************!*\
  !*** ./src/app/modules/auth/components/register/register.component.ngfactory.js ***!
  \**********************************************************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
Object.defineProperty(exports, "__esModule", { value: true });
const i0 = __webpack_require__(/*! ./register.component.scss.shim.ngstyle */ "./src/app/modules/auth/components/register/register.component.scss.shim.ngstyle.js");
const i1 = __webpack_require__(/*! @angular/core */ "@angular/core");
const i2 = __webpack_require__(/*! @angular/forms */ "@angular/forms");
const i3 = __webpack_require__(/*! @angular/router */ "@angular/router");
const i4 = __webpack_require__(/*! ./register.component */ "./src/app/modules/auth/components/register/register.component.ts");
const i5 = __webpack_require__(/*! ../../services/auth.service */ "./src/app/modules/auth/services/auth.service.ts");
var styles_RegisterComponent = [i0.styles];
var RenderType_RegisterComponent = i1.ɵcrt({ encapsulation: 0, styles: styles_RegisterComponent, data: {} });
exports.RenderType_RegisterComponent = RenderType_RegisterComponent;
function View_RegisterComponent_0(_l) { return i1.ɵvid(0, [(_l()(), i1.ɵeld(0, 0, null, null, 41, "div", [["class", "responsive-flex-wrapper"]], null, null, null, null, null)), (_l()(), i1.ɵeld(1, 0, null, null, 40, "div", [["class", "form-wrapper"]], null, null, null, null, null)), (_l()(), i1.ɵeld(2, 0, null, null, 1, "div", [["class", "form-title"]], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, ["Register"])), (_l()(), i1.ɵeld(4, 0, null, null, 37, "form", [["novalidate", ""]], [[2, "ng-untouched", null], [2, "ng-touched", null], [2, "ng-pristine", null], [2, "ng-dirty", null], [2, "ng-valid", null], [2, "ng-invalid", null], [2, "ng-pending", null]], [[null, "submit"], [null, "reset"]], function (_v, en, $event) { var ad = true; if (("submit" === en)) {
        var pd_0 = (i1.ɵnov(_v, 6).onSubmit($event) !== false);
        ad = (pd_0 && ad);
    } if (("reset" === en)) {
        var pd_1 = (i1.ɵnov(_v, 6).onReset() !== false);
        ad = (pd_1 && ad);
    } return ad; }, null, null)), i1.ɵdid(5, 16384, null, 0, i2.ɵangular_packages_forms_forms_z, [], null, null), i1.ɵdid(6, 540672, null, 0, i2.FormGroupDirective, [[8, null], [8, null]], { form: [0, "form"] }, null), i1.ɵprd(2048, null, i2.ControlContainer, null, [i2.FormGroupDirective]), i1.ɵdid(8, 16384, null, 0, i2.NgControlStatusGroup, [[4, i2.ControlContainer]], null, null), (_l()(), i1.ɵeld(9, 0, null, null, 8, "div", [["class", "form-group"]], null, null, null, null, null)), (_l()(), i1.ɵeld(10, 0, null, null, 1, "label", [["for", "register-email"]], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, ["Email address"])), (_l()(), i1.ɵeld(12, 0, null, null, 5, "input", [["class", "form-control"], ["formControlName", "email"], ["id", "register-email"], ["placeholder", "Email"], ["type", "email"]], [[2, "ng-untouched", null], [2, "ng-touched", null], [2, "ng-pristine", null], [2, "ng-dirty", null], [2, "ng-valid", null], [2, "ng-invalid", null], [2, "ng-pending", null]], [[null, "input"], [null, "blur"], [null, "compositionstart"], [null, "compositionend"]], function (_v, en, $event) { var ad = true; if (("input" === en)) {
        var pd_0 = (i1.ɵnov(_v, 13)._handleInput($event.target.value) !== false);
        ad = (pd_0 && ad);
    } if (("blur" === en)) {
        var pd_1 = (i1.ɵnov(_v, 13).onTouched() !== false);
        ad = (pd_1 && ad);
    } if (("compositionstart" === en)) {
        var pd_2 = (i1.ɵnov(_v, 13)._compositionStart() !== false);
        ad = (pd_2 && ad);
    } if (("compositionend" === en)) {
        var pd_3 = (i1.ɵnov(_v, 13)._compositionEnd($event.target.value) !== false);
        ad = (pd_3 && ad);
    } return ad; }, null, null)), i1.ɵdid(13, 16384, null, 0, i2.DefaultValueAccessor, [i1.Renderer2, i1.ElementRef, [2, i2.COMPOSITION_BUFFER_MODE]], null, null), i1.ɵprd(1024, null, i2.NG_VALUE_ACCESSOR, function (p0_0) { return [p0_0]; }, [i2.DefaultValueAccessor]), i1.ɵdid(15, 671744, null, 0, i2.FormControlName, [[3, i2.ControlContainer], [8, null], [8, null], [6, i2.NG_VALUE_ACCESSOR], [2, i2.ɵangular_packages_forms_forms_q]], { name: [0, "name"] }, null), i1.ɵprd(2048, null, i2.NgControl, null, [i2.FormControlName]), i1.ɵdid(17, 16384, null, 0, i2.NgControlStatus, [[4, i2.NgControl]], null, null), (_l()(), i1.ɵeld(18, 0, null, null, 8, "div", [["class", "form-group"]], null, null, null, null, null)), (_l()(), i1.ɵeld(19, 0, null, null, 1, "label", [["for", "register-passowrd"]], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, ["Password"])), (_l()(), i1.ɵeld(21, 0, null, null, 5, "input", [["class", "form-control"], ["formControlName", "password"], ["id", "register-passowrd"], ["placeholder", "Password"], ["type", "password"]], [[2, "ng-untouched", null], [2, "ng-touched", null], [2, "ng-pristine", null], [2, "ng-dirty", null], [2, "ng-valid", null], [2, "ng-invalid", null], [2, "ng-pending", null]], [[null, "input"], [null, "blur"], [null, "compositionstart"], [null, "compositionend"]], function (_v, en, $event) { var ad = true; if (("input" === en)) {
        var pd_0 = (i1.ɵnov(_v, 22)._handleInput($event.target.value) !== false);
        ad = (pd_0 && ad);
    } if (("blur" === en)) {
        var pd_1 = (i1.ɵnov(_v, 22).onTouched() !== false);
        ad = (pd_1 && ad);
    } if (("compositionstart" === en)) {
        var pd_2 = (i1.ɵnov(_v, 22)._compositionStart() !== false);
        ad = (pd_2 && ad);
    } if (("compositionend" === en)) {
        var pd_3 = (i1.ɵnov(_v, 22)._compositionEnd($event.target.value) !== false);
        ad = (pd_3 && ad);
    } return ad; }, null, null)), i1.ɵdid(22, 16384, null, 0, i2.DefaultValueAccessor, [i1.Renderer2, i1.ElementRef, [2, i2.COMPOSITION_BUFFER_MODE]], null, null), i1.ɵprd(1024, null, i2.NG_VALUE_ACCESSOR, function (p0_0) { return [p0_0]; }, [i2.DefaultValueAccessor]), i1.ɵdid(24, 671744, null, 0, i2.FormControlName, [[3, i2.ControlContainer], [8, null], [8, null], [6, i2.NG_VALUE_ACCESSOR], [2, i2.ɵangular_packages_forms_forms_q]], { name: [0, "name"] }, null), i1.ɵprd(2048, null, i2.NgControl, null, [i2.FormControlName]), i1.ɵdid(26, 16384, null, 0, i2.NgControlStatus, [[4, i2.NgControl]], null, null), (_l()(), i1.ɵeld(27, 0, null, null, 8, "div", [["class", "form-group"]], null, null, null, null, null)), (_l()(), i1.ɵeld(28, 0, null, null, 1, "label", [["for", "register-confirm-passowrd"]], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, ["Confirm Password"])), (_l()(), i1.ɵeld(30, 0, null, null, 5, "input", [["class", "form-control"], ["formControlName", "confirmPassword"], ["id", "register-confirm-passowrd"], ["placeholder", "Confirm Password"], ["type", "password"]], [[2, "ng-untouched", null], [2, "ng-touched", null], [2, "ng-pristine", null], [2, "ng-dirty", null], [2, "ng-valid", null], [2, "ng-invalid", null], [2, "ng-pending", null]], [[null, "input"], [null, "blur"], [null, "compositionstart"], [null, "compositionend"]], function (_v, en, $event) { var ad = true; if (("input" === en)) {
        var pd_0 = (i1.ɵnov(_v, 31)._handleInput($event.target.value) !== false);
        ad = (pd_0 && ad);
    } if (("blur" === en)) {
        var pd_1 = (i1.ɵnov(_v, 31).onTouched() !== false);
        ad = (pd_1 && ad);
    } if (("compositionstart" === en)) {
        var pd_2 = (i1.ɵnov(_v, 31)._compositionStart() !== false);
        ad = (pd_2 && ad);
    } if (("compositionend" === en)) {
        var pd_3 = (i1.ɵnov(_v, 31)._compositionEnd($event.target.value) !== false);
        ad = (pd_3 && ad);
    } return ad; }, null, null)), i1.ɵdid(31, 16384, null, 0, i2.DefaultValueAccessor, [i1.Renderer2, i1.ElementRef, [2, i2.COMPOSITION_BUFFER_MODE]], null, null), i1.ɵprd(1024, null, i2.NG_VALUE_ACCESSOR, function (p0_0) { return [p0_0]; }, [i2.DefaultValueAccessor]), i1.ɵdid(33, 671744, null, 0, i2.FormControlName, [[3, i2.ControlContainer], [8, null], [8, null], [6, i2.NG_VALUE_ACCESSOR], [2, i2.ɵangular_packages_forms_forms_q]], { name: [0, "name"] }, null), i1.ɵprd(2048, null, i2.NgControl, null, [i2.FormControlName]), i1.ɵdid(35, 16384, null, 0, i2.NgControlStatus, [[4, i2.NgControl]], null, null), (_l()(), i1.ɵeld(36, 0, null, null, 1, "button", [["class", "btn btn-primary float-right"]], [[8, "disabled", 0]], [[null, "click"]], function (_v, en, $event) { var ad = true; var _co = _v.component; if (("click" === en)) {
        var pd_0 = (_co.onRegister() !== false);
        ad = (pd_0 && ad);
    } return ad; }, null, null)), (_l()(), i1.ɵted(-1, null, ["Register"])), (_l()(), i1.ɵeld(38, 0, null, null, 3, "button", [["class", "btn btn-success float-right mr-2"]], null, [[null, "click"]], function (_v, en, $event) { var ad = true; if (("click" === en)) {
        var pd_0 = (i1.ɵnov(_v, 39).onClick() !== false);
        ad = (pd_0 && ad);
    } return ad; }, null, null)), i1.ɵdid(39, 16384, null, 0, i3.RouterLink, [i3.Router, i3.ActivatedRoute, [8, null], i1.Renderer2, i1.ElementRef], { routerLink: [0, "routerLink"] }, null), i1.ɵpad(40, 1), (_l()(), i1.ɵted(-1, null, ["Login"]))], function (_ck, _v) { var _co = _v.component; var currVal_7 = _co.registerForm; _ck(_v, 6, 0, currVal_7); var currVal_15 = "email"; _ck(_v, 15, 0, currVal_15); var currVal_23 = "password"; _ck(_v, 24, 0, currVal_23); var currVal_31 = "confirmPassword"; _ck(_v, 33, 0, currVal_31); var currVal_33 = _ck(_v, 40, 0, "/login"); _ck(_v, 39, 0, currVal_33); }, function (_ck, _v) { var _co = _v.component; var currVal_0 = i1.ɵnov(_v, 8).ngClassUntouched; var currVal_1 = i1.ɵnov(_v, 8).ngClassTouched; var currVal_2 = i1.ɵnov(_v, 8).ngClassPristine; var currVal_3 = i1.ɵnov(_v, 8).ngClassDirty; var currVal_4 = i1.ɵnov(_v, 8).ngClassValid; var currVal_5 = i1.ɵnov(_v, 8).ngClassInvalid; var currVal_6 = i1.ɵnov(_v, 8).ngClassPending; _ck(_v, 4, 0, currVal_0, currVal_1, currVal_2, currVal_3, currVal_4, currVal_5, currVal_6); var currVal_8 = i1.ɵnov(_v, 17).ngClassUntouched; var currVal_9 = i1.ɵnov(_v, 17).ngClassTouched; var currVal_10 = i1.ɵnov(_v, 17).ngClassPristine; var currVal_11 = i1.ɵnov(_v, 17).ngClassDirty; var currVal_12 = i1.ɵnov(_v, 17).ngClassValid; var currVal_13 = i1.ɵnov(_v, 17).ngClassInvalid; var currVal_14 = i1.ɵnov(_v, 17).ngClassPending; _ck(_v, 12, 0, currVal_8, currVal_9, currVal_10, currVal_11, currVal_12, currVal_13, currVal_14); var currVal_16 = i1.ɵnov(_v, 26).ngClassUntouched; var currVal_17 = i1.ɵnov(_v, 26).ngClassTouched; var currVal_18 = i1.ɵnov(_v, 26).ngClassPristine; var currVal_19 = i1.ɵnov(_v, 26).ngClassDirty; var currVal_20 = i1.ɵnov(_v, 26).ngClassValid; var currVal_21 = i1.ɵnov(_v, 26).ngClassInvalid; var currVal_22 = i1.ɵnov(_v, 26).ngClassPending; _ck(_v, 21, 0, currVal_16, currVal_17, currVal_18, currVal_19, currVal_20, currVal_21, currVal_22); var currVal_24 = i1.ɵnov(_v, 35).ngClassUntouched; var currVal_25 = i1.ɵnov(_v, 35).ngClassTouched; var currVal_26 = i1.ɵnov(_v, 35).ngClassPristine; var currVal_27 = i1.ɵnov(_v, 35).ngClassDirty; var currVal_28 = i1.ɵnov(_v, 35).ngClassValid; var currVal_29 = i1.ɵnov(_v, 35).ngClassInvalid; var currVal_30 = i1.ɵnov(_v, 35).ngClassPending; _ck(_v, 30, 0, currVal_24, currVal_25, currVal_26, currVal_27, currVal_28, currVal_29, currVal_30); var currVal_32 = !_co.registerForm.valid; _ck(_v, 36, 0, currVal_32); }); }
exports.View_RegisterComponent_0 = View_RegisterComponent_0;
function View_RegisterComponent_Host_0(_l) { return i1.ɵvid(0, [(_l()(), i1.ɵeld(0, 0, null, null, 1, "app-register", [], null, null, null, View_RegisterComponent_0, RenderType_RegisterComponent)), i1.ɵdid(1, 114688, null, 0, i4.RegisterComponent, [i5.AuthService, i3.Router], null, null)], function (_ck, _v) { _ck(_v, 1, 0); }, null); }
exports.View_RegisterComponent_Host_0 = View_RegisterComponent_Host_0;
var RegisterComponentNgFactory = i1.ɵccf("app-register", i4.RegisterComponent, View_RegisterComponent_Host_0, {}, {}, []);
exports.RegisterComponentNgFactory = RegisterComponentNgFactory;


/***/ }),

/***/ "./src/app/modules/auth/components/register/register.component.scss.shim.ngstyle.js":
/*!******************************************************************************************!*\
  !*** ./src/app/modules/auth/components/register/register.component.scss.shim.ngstyle.js ***!
  \******************************************************************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
Object.defineProperty(exports, "__esModule", { value: true });
var styles = ["\n/*# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IiIsImZpbGUiOiJzcmMvYXBwL21vZHVsZXMvYXV0aC9jb21wb25lbnRzL3JlZ2lzdGVyL3JlZ2lzdGVyLmNvbXBvbmVudC5zY3NzIn0= */"];
exports.styles = styles;


/***/ }),

/***/ "./src/app/modules/auth/components/register/register.component.ts":
/*!************************************************************************!*\
  !*** ./src/app/modules/auth/components/register/register.component.ts ***!
  \************************************************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

Object.defineProperty(exports, "__esModule", { value: true });
const core_1 = __webpack_require__(/*! @angular/core */ "@angular/core");
const forms_1 = __webpack_require__(/*! @angular/forms */ "@angular/forms");
class RegisterComponent {
    constructor(authService, router) {
        this.authService = authService;
        this.router = router;
        this.registerForm = new forms_1.FormGroup({
            email: new forms_1.FormControl('', [forms_1.Validators.required, forms_1.Validators.email]),
            password: new forms_1.FormControl('', [forms_1.Validators.required]),
            confirmPassword: new forms_1.FormControl('', [forms_1.Validators.required])
        });
    }
    ngOnInit() { }
    onRegister() {
        const email = this.registerForm.controls['email'].value;
        const password = this.registerForm.controls['password'].value;
        const confirmPassword = this.registerForm.controls['confirmPassword'].value;
        if (password !== confirmPassword) {
            return;
        }
        this.authService.register(email, password)
            .subscribe(() => {
            this.router.navigate(['/busses']);
        });
    }
}
exports.RegisterComponent = RegisterComponent;


/***/ }),

/***/ "./src/app/modules/auth/services/auth.service.ts":
/*!*******************************************************!*\
  !*** ./src/app/modules/auth/services/auth.service.ts ***!
  \*******************************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

Object.defineProperty(exports, "__esModule", { value: true });
const operators_1 = __webpack_require__(/*! rxjs/operators */ "rxjs/operators");
const constants_1 = __webpack_require__(/*! ../../../constants */ "./src/app/constants.ts");
class AuthService {
    constructor(httpClient, constants, storageService) {
        this.httpClient = httpClient;
        this.constants = constants;
        this.storageService = storageService;
    }
    register(email, password) {
        return this.httpClient.post(`${this.constants.apiURL}/auth/local/signup`, { email, password }).pipe(operators_1.map(response => {
            this.storageService.setItem(constants_1.JWT_KEY, response.token);
            return response;
        }));
    }
    login(email, password) {
        return this.httpClient.post(`${this.constants.apiURL}/auth/local/signin`, { email, password }).pipe(operators_1.map(response => {
            this.storageService.setItem(constants_1.JWT_KEY, response.token);
            return response;
        }));
    }
}
exports.AuthService = AuthService;


/***/ }),

/***/ "./src/app/modules/busses/busses.module.ngfactory.js":
/*!***********************************************************!*\
  !*** ./src/app/modules/busses/busses.module.ngfactory.js ***!
  \***********************************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
Object.defineProperty(exports, "__esModule", { value: true });
const i0 = __webpack_require__(/*! @angular/core */ "@angular/core");
const i1 = __webpack_require__(/*! ./busses.module */ "./src/app/modules/busses/busses.module.ts");
const i2 = __webpack_require__(/*! ../../../../node_modules/@angular/router/router.ngfactory */ "./node_modules/@angular/router/router.ngfactory.js");
const i3 = __webpack_require__(/*! ./components/busses/busses.component.ngfactory */ "./src/app/modules/busses/components/busses/busses.component.ngfactory.js");
const i4 = __webpack_require__(/*! ./components/admin/admin.component.ngfactory */ "./src/app/modules/busses/components/admin/admin.component.ngfactory.js");
const i5 = __webpack_require__(/*! @angular/common */ "@angular/common");
const i6 = __webpack_require__(/*! @angular/forms */ "@angular/forms");
const i7 = __webpack_require__(/*! ./services/busses.service */ "./src/app/modules/busses/services/busses.service.ts");
const i8 = __webpack_require__(/*! @angular/common/http */ "@angular/common/http");
const i9 = __webpack_require__(/*! ../shared/config/constants.config */ "./src/app/modules/shared/config/constants.config.ts");
const i10 = __webpack_require__(/*! @angular/router */ "@angular/router");
const i11 = __webpack_require__(/*! ../shared/shared.module */ "./src/app/modules/shared/shared.module.ts");
const i12 = __webpack_require__(/*! ./busses.routing.module */ "./src/app/modules/busses/busses.routing.module.ts");
const i13 = __webpack_require__(/*! ./components/busses/busses.component */ "./src/app/modules/busses/components/busses/busses.component.ts");
const i14 = __webpack_require__(/*! ../shared/guards/auth.guard */ "./src/app/modules/shared/guards/auth.guard.ts");
const i15 = __webpack_require__(/*! ./components/admin/admin.component */ "./src/app/modules/busses/components/admin/admin.component.ts");
var BussesModuleNgFactory = i0.ɵcmf(i1.BussesModule, [], function (_l) { return i0.ɵmod([i0.ɵmpd(512, i0.ComponentFactoryResolver, i0.ɵCodegenComponentFactoryResolver, [[8, [i2.ɵangular_packages_router_router_lNgFactory, i3.BussesComponentNgFactory, i4.AdminComponentNgFactory]], [3, i0.ComponentFactoryResolver], i0.NgModuleRef]), i0.ɵmpd(4608, i5.NgLocalization, i5.NgLocaleLocalization, [i0.LOCALE_ID, [2, i5.ɵangular_packages_common_common_a]]), i0.ɵmpd(4608, i6.ɵangular_packages_forms_forms_o, i6.ɵangular_packages_forms_forms_o, []), i0.ɵmpd(4608, i6.FormBuilder, i6.FormBuilder, []), i0.ɵmpd(4608, i7.BussesService, i7.BussesService, [i8.HttpClient, i9.Constants]), i0.ɵmpd(1073742336, i5.CommonModule, i5.CommonModule, []), i0.ɵmpd(1073742336, i10.RouterModule, i10.RouterModule, [[2, i10.ɵangular_packages_router_router_a], [2, i10.Router]]), i0.ɵmpd(1073742336, i6.ɵangular_packages_forms_forms_d, i6.ɵangular_packages_forms_forms_d, []), i0.ɵmpd(1073742336, i6.FormsModule, i6.FormsModule, []), i0.ɵmpd(1073742336, i6.ReactiveFormsModule, i6.ReactiveFormsModule, []), i0.ɵmpd(1073742336, i11.SharedModule, i11.SharedModule, []), i0.ɵmpd(1073742336, i12.BussesRoutingModule, i12.BussesRoutingModule, []), i0.ɵmpd(1073742336, i1.BussesModule, i1.BussesModule, []), i0.ɵmpd(1024, i10.ROUTES, function () { return [[{ path: "", component: i13.BussesComponent, canActivate: [i14.AuthGuard] }, { path: "admin", component: i15.AdminComponent, canActivate: [i14.AuthGuard] }]]; }, [])]); });
exports.BussesModuleNgFactory = BussesModuleNgFactory;


/***/ }),

/***/ "./src/app/modules/busses/busses.module.ts":
/*!*************************************************!*\
  !*** ./src/app/modules/busses/busses.module.ts ***!
  \*************************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

Object.defineProperty(exports, "__esModule", { value: true });
class BussesModule {
}
exports.BussesModule = BussesModule;


/***/ }),

/***/ "./src/app/modules/busses/busses.routing.module.ts":
/*!*********************************************************!*\
  !*** ./src/app/modules/busses/busses.routing.module.ts ***!
  \*********************************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

Object.defineProperty(exports, "__esModule", { value: true });
const router_1 = __webpack_require__(/*! @angular/router */ "@angular/router");
const busses_component_1 = __webpack_require__(/*! ./components/busses/busses.component */ "./src/app/modules/busses/components/busses/busses.component.ts");
const auth_guard_1 = __webpack_require__(/*! ../shared/guards/auth.guard */ "./src/app/modules/shared/guards/auth.guard.ts");
const admin_component_1 = __webpack_require__(/*! ./components/admin/admin.component */ "./src/app/modules/busses/components/admin/admin.component.ts");
const routes = [
    {
        path: '',
        component: busses_component_1.BussesComponent,
        canActivate: [auth_guard_1.AuthGuard]
    },
    {
        path: 'admin',
        component: admin_component_1.AdminComponent,
        canActivate: [auth_guard_1.AuthGuard]
    }
];
class BussesRoutingModule {
}
exports.BussesRoutingModule = BussesRoutingModule;


/***/ }),

/***/ "./src/app/modules/busses/components/admin/admin.component.ngfactory.js":
/*!******************************************************************************!*\
  !*** ./src/app/modules/busses/components/admin/admin.component.ngfactory.js ***!
  \******************************************************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
Object.defineProperty(exports, "__esModule", { value: true });
const i0 = __webpack_require__(/*! ./admin.component.scss.shim.ngstyle */ "./src/app/modules/busses/components/admin/admin.component.scss.shim.ngstyle.js");
const i1 = __webpack_require__(/*! @angular/core */ "@angular/core");
const i2 = __webpack_require__(/*! @angular/common */ "@angular/common");
const i3 = __webpack_require__(/*! ./admin.component */ "./src/app/modules/busses/components/admin/admin.component.ts");
const i4 = __webpack_require__(/*! ../../services/busses.service */ "./src/app/modules/busses/services/busses.service.ts");
var styles_AdminComponent = [i0.styles];
var RenderType_AdminComponent = i1.ɵcrt({ encapsulation: 0, styles: styles_AdminComponent, data: {} });
exports.RenderType_AdminComponent = RenderType_AdminComponent;
function View_AdminComponent_1(_l) { return i1.ɵvid(0, [(_l()(), i1.ɵeld(0, 0, null, null, 2, "div", [["class", "row"]], null, null, null, null, null)), (_l()(), i1.ɵeld(1, 0, null, null, 1, "div", [["class", "col-12"]], null, null, null, null, null)), (_l()(), i1.ɵted(2, null, ["", ""]))], null, function (_ck, _v) { var currVal_0 = _v.context.$implicit.title; _ck(_v, 2, 0, currVal_0); }); }
function View_AdminComponent_0(_l) { return i1.ɵvid(0, [i1.ɵqud(402653184, 1, { lineInput: 0 }), (_l()(), i1.ɵeld(1, 0, null, null, 5, "div", [["class", "row"]], null, null, null, null, null)), (_l()(), i1.ɵeld(2, 0, null, null, 1, "div", [["class", "col-8"]], null, null, null, null, null)), (_l()(), i1.ɵeld(3, 0, [[1, 0], ["lineInput", 1]], null, 0, "input", [["class", "form-control"], ["placeholder", "Line Title"], ["type", "text"]], null, null, null, null, null)), (_l()(), i1.ɵeld(4, 0, null, null, 2, "div", [["class", "col-4"]], null, null, null, null, null)), (_l()(), i1.ɵeld(5, 0, null, null, 1, "button", [["class", "btn btn-block btn-success"], ["type", "button"]], null, [[null, "click"]], function (_v, en, $event) { var ad = true; var _co = _v.component; if (("click" === en)) {
        var pd_0 = (_co.onCreateLine() !== false);
        ad = (pd_0 && ad);
    } return ad; }, null, null)), (_l()(), i1.ɵted(-1, null, ["Create Line"])), (_l()(), i1.ɵand(16777216, null, null, 2, null, View_AdminComponent_1)), i1.ɵdid(8, 278528, null, 0, i2.NgForOf, [i1.ViewContainerRef, i1.TemplateRef, i1.IterableDiffers], { ngForOf: [0, "ngForOf"] }, null), i1.ɵpid(131072, i2.AsyncPipe, [i1.ChangeDetectorRef])], function (_ck, _v) { var _co = _v.component; var currVal_0 = i1.ɵunv(_v, 8, 0, i1.ɵnov(_v, 9).transform(_co.lines)); _ck(_v, 8, 0, currVal_0); }, null); }
exports.View_AdminComponent_0 = View_AdminComponent_0;
function View_AdminComponent_Host_0(_l) { return i1.ɵvid(0, [(_l()(), i1.ɵeld(0, 0, null, null, 1, "app-admin-component", [], null, null, null, View_AdminComponent_0, RenderType_AdminComponent)), i1.ɵdid(1, 114688, null, 0, i3.AdminComponent, [i4.BussesService], null, null)], function (_ck, _v) { _ck(_v, 1, 0); }, null); }
exports.View_AdminComponent_Host_0 = View_AdminComponent_Host_0;
var AdminComponentNgFactory = i1.ɵccf("app-admin-component", i3.AdminComponent, View_AdminComponent_Host_0, {}, {}, []);
exports.AdminComponentNgFactory = AdminComponentNgFactory;


/***/ }),

/***/ "./src/app/modules/busses/components/admin/admin.component.scss.shim.ngstyle.js":
/*!**************************************************************************************!*\
  !*** ./src/app/modules/busses/components/admin/admin.component.scss.shim.ngstyle.js ***!
  \**************************************************************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
Object.defineProperty(exports, "__esModule", { value: true });
var styles = ["\n/*# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IiIsImZpbGUiOiJzcmMvYXBwL21vZHVsZXMvYnVzc2VzL2NvbXBvbmVudHMvYWRtaW4vYWRtaW4uY29tcG9uZW50LnNjc3MifQ== */"];
exports.styles = styles;


/***/ }),

/***/ "./src/app/modules/busses/components/admin/admin.component.ts":
/*!********************************************************************!*\
  !*** ./src/app/modules/busses/components/admin/admin.component.ts ***!
  \********************************************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

Object.defineProperty(exports, "__esModule", { value: true });
const core_1 = __webpack_require__(/*! @angular/core */ "@angular/core");
class AdminComponent {
    constructor(bussesService) {
        this.bussesService = bussesService;
    }
    ngOnInit() {
        this.initLines();
    }
    onCreateLine() {
        const title = this.lineInput.nativeElement.value;
        this.bussesService.createLine({ title })
            .subscribe(() => {
            this.initLines();
        });
    }
    initLines() {
        this.lines = this.bussesService.getLines();
    }
    init() {
        this.initLines();
    }
}
exports.AdminComponent = AdminComponent;


/***/ }),

/***/ "./src/app/modules/busses/components/busses/busses.component.ngfactory.js":
/*!********************************************************************************!*\
  !*** ./src/app/modules/busses/components/busses/busses.component.ngfactory.js ***!
  \********************************************************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
Object.defineProperty(exports, "__esModule", { value: true });
const i0 = __webpack_require__(/*! ./busses.component.scss.shim.ngstyle */ "./src/app/modules/busses/components/busses/busses.component.scss.shim.ngstyle.js");
const i1 = __webpack_require__(/*! @angular/core */ "@angular/core");
const i2 = __webpack_require__(/*! ../lines/lines.component.ngfactory */ "./src/app/modules/busses/components/lines/lines.component.ngfactory.js");
const i3 = __webpack_require__(/*! ../lines/lines.component */ "./src/app/modules/busses/components/lines/lines.component.ts");
const i4 = __webpack_require__(/*! ./busses.component */ "./src/app/modules/busses/components/busses/busses.component.ts");
const i5 = __webpack_require__(/*! ../../services/busses.service */ "./src/app/modules/busses/services/busses.service.ts");
var styles_BussesComponent = [i0.styles];
var RenderType_BussesComponent = i1.ɵcrt({ encapsulation: 0, styles: styles_BussesComponent, data: {} });
exports.RenderType_BussesComponent = RenderType_BussesComponent;
function View_BussesComponent_0(_l) { return i1.ɵvid(0, [(_l()(), i1.ɵeld(0, 0, null, null, 1, "app-lines", [], null, null, null, i2.View_LinesComponent_0, i2.RenderType_LinesComponent)), i1.ɵdid(1, 114688, null, 0, i3.LinesComponent, [], null, null)], function (_ck, _v) { _ck(_v, 1, 0); }, null); }
exports.View_BussesComponent_0 = View_BussesComponent_0;
function View_BussesComponent_Host_0(_l) { return i1.ɵvid(0, [(_l()(), i1.ɵeld(0, 0, null, null, 1, "app-busses", [], null, null, null, View_BussesComponent_0, RenderType_BussesComponent)), i1.ɵdid(1, 114688, null, 0, i4.BussesComponent, [i5.BussesService], null, null)], function (_ck, _v) { _ck(_v, 1, 0); }, null); }
exports.View_BussesComponent_Host_0 = View_BussesComponent_Host_0;
var BussesComponentNgFactory = i1.ɵccf("app-busses", i4.BussesComponent, View_BussesComponent_Host_0, {}, {}, []);
exports.BussesComponentNgFactory = BussesComponentNgFactory;


/***/ }),

/***/ "./src/app/modules/busses/components/busses/busses.component.scss.shim.ngstyle.js":
/*!****************************************************************************************!*\
  !*** ./src/app/modules/busses/components/busses/busses.component.scss.shim.ngstyle.js ***!
  \****************************************************************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
Object.defineProperty(exports, "__esModule", { value: true });
var styles = ["\n/*# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IiIsImZpbGUiOiJzcmMvYXBwL21vZHVsZXMvYnVzc2VzL2NvbXBvbmVudHMvYnVzc2VzL2J1c3Nlcy5jb21wb25lbnQuc2NzcyJ9 */"];
exports.styles = styles;


/***/ }),

/***/ "./src/app/modules/busses/components/busses/busses.component.ts":
/*!**********************************************************************!*\
  !*** ./src/app/modules/busses/components/busses/busses.component.ts ***!
  \**********************************************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

Object.defineProperty(exports, "__esModule", { value: true });
const core_1 = __webpack_require__(/*! @angular/core */ "@angular/core");
class BussesComponent {
    constructor(bussesService) {
        this.bussesService = bussesService;
    }
    ngOnInit() {
    }
}
exports.BussesComponent = BussesComponent;


/***/ }),

/***/ "./src/app/modules/busses/components/lines/lines.component.ngfactory.js":
/*!******************************************************************************!*\
  !*** ./src/app/modules/busses/components/lines/lines.component.ngfactory.js ***!
  \******************************************************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
Object.defineProperty(exports, "__esModule", { value: true });
const i0 = __webpack_require__(/*! ./lines.component.scss.shim.ngstyle */ "./src/app/modules/busses/components/lines/lines.component.scss.shim.ngstyle.js");
const i1 = __webpack_require__(/*! @angular/core */ "@angular/core");
const i2 = __webpack_require__(/*! @angular/common */ "@angular/common");
const i3 = __webpack_require__(/*! ./lines.component */ "./src/app/modules/busses/components/lines/lines.component.ts");
var styles_LinesComponent = [i0.styles];
var RenderType_LinesComponent = i1.ɵcrt({ encapsulation: 0, styles: styles_LinesComponent, data: {} });
exports.RenderType_LinesComponent = RenderType_LinesComponent;
function View_LinesComponent_1(_l) { return i1.ɵvid(0, [(_l()(), i1.ɵeld(0, 0, null, null, 2, "a", [], null, null, null, null, null)), (_l()(), i1.ɵeld(1, 0, null, null, 1, "button", [["class", "btn on"]], null, null, null, null, null)), (_l()(), i1.ɵted(2, null, ["", ""]))], null, function (_ck, _v) { var currVal_0 = _v.context.$implicit; _ck(_v, 2, 0, currVal_0); }); }
function View_LinesComponent_0(_l) { return i1.ɵvid(0, [(_l()(), i1.ɵand(16777216, null, null, 1, null, View_LinesComponent_1)), i1.ɵdid(1, 278528, null, 0, i2.NgForOf, [i1.ViewContainerRef, i1.TemplateRef, i1.IterableDiffers], { ngForOf: [0, "ngForOf"] }, null)], function (_ck, _v) { var _co = _v.component; var currVal_0 = _co.lines; _ck(_v, 1, 0, currVal_0); }, null); }
exports.View_LinesComponent_0 = View_LinesComponent_0;
function View_LinesComponent_Host_0(_l) { return i1.ɵvid(0, [(_l()(), i1.ɵeld(0, 0, null, null, 1, "app-lines", [], null, null, null, View_LinesComponent_0, RenderType_LinesComponent)), i1.ɵdid(1, 114688, null, 0, i3.LinesComponent, [], null, null)], function (_ck, _v) { _ck(_v, 1, 0); }, null); }
exports.View_LinesComponent_Host_0 = View_LinesComponent_Host_0;
var LinesComponentNgFactory = i1.ɵccf("app-lines", i3.LinesComponent, View_LinesComponent_Host_0, {}, {}, []);
exports.LinesComponentNgFactory = LinesComponentNgFactory;


/***/ }),

/***/ "./src/app/modules/busses/components/lines/lines.component.scss.shim.ngstyle.js":
/*!**************************************************************************************!*\
  !*** ./src/app/modules/busses/components/lines/lines.component.scss.shim.ngstyle.js ***!
  \**************************************************************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
Object.defineProperty(exports, "__esModule", { value: true });
var styles = [".btn[_ngcontent-%COMP%] {\n  border: none;\n  color: white;\n  padding: 14px 66px;\n  cursor: pointer;\n}\n\n.ok[_ngcontent-%COMP%] {\n  background-color: #2196f3;\n}\n\n.ok[_ngcontent-%COMP%]:hover {\n  background: #0b7dda;\n}\n\n.btn2[_ngcontent-%COMP%] {\n  border: none;\n  color: white;\n  padding: 20px 34px;\n  font-size: 16px;\n  cursor: pointer;\n}\n\n.guest[_ngcontent-%COMP%] {\n  background-color: #2196f3;\n}\n\n.guest[_ngcontent-%COMP%]:hover {\n  background: #0b7dda;\n}\n/*# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbInNyYy9hcHAvbW9kdWxlcy9idXNzZXMvY29tcG9uZW50cy9saW5lcy9EOlxcQU5HVUxBUlxcQnVzc2VzXFxidXNzZXMtZmUvc3JjXFxhcHBcXG1vZHVsZXNcXGJ1c3Nlc1xcY29tcG9uZW50c1xcbGluZXNcXGxpbmVzLmNvbXBvbmVudC5zY3NzIiwic3JjL2FwcC9tb2R1bGVzL2J1c3Nlcy9jb21wb25lbnRzL2xpbmVzL2xpbmVzLmNvbXBvbmVudC5zY3NzIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiJBQUFBO0VBQ0UsWUFBQTtFQUNBLFlBQUE7RUFDQSxrQkFBQTtFQUNBLGVBQUE7QUNDRjs7QURDQTtFQUNFLHlCQUFBO0FDRUY7O0FEQUE7RUFDRSxtQkFBQTtBQ0dGOztBREFBO0VBQ0UsWUFBQTtFQUNBLFlBQUE7RUFDQSxrQkFBQTtFQUNBLGVBQUE7RUFDQSxlQUFBO0FDR0Y7O0FEQUE7RUFDRSx5QkFBQTtBQ0dGOztBRERBO0VBQ0UsbUJBQUE7QUNJRiIsImZpbGUiOiJzcmMvYXBwL21vZHVsZXMvYnVzc2VzL2NvbXBvbmVudHMvbGluZXMvbGluZXMuY29tcG9uZW50LnNjc3MiLCJzb3VyY2VzQ29udGVudCI6WyIuYnRuIHtcclxuICBib3JkZXI6IG5vbmU7XHJcbiAgY29sb3I6IHdoaXRlO1xyXG4gIHBhZGRpbmc6IDE0cHggNjZweDtcclxuICBjdXJzb3I6IHBvaW50ZXI7XHJcbn1cclxuLm9rIHtcclxuICBiYWNrZ3JvdW5kLWNvbG9yOiAjMjE5NmYzO1xyXG59XHJcbi5vazpob3ZlciB7XHJcbiAgYmFja2dyb3VuZDogIzBiN2RkYTtcclxufVxyXG5cclxuLmJ0bjIge1xyXG4gIGJvcmRlcjogbm9uZTtcclxuICBjb2xvcjogd2hpdGU7XHJcbiAgcGFkZGluZzogMjBweCAzNHB4O1xyXG4gIGZvbnQtc2l6ZTogMTZweDtcclxuICBjdXJzb3I6IHBvaW50ZXI7XHJcbn1cclxuXHJcbi5ndWVzdCB7XHJcbiAgYmFja2dyb3VuZC1jb2xvcjogIzIxOTZmMztcclxufVxyXG4uZ3Vlc3Q6aG92ZXIge1xyXG4gIGJhY2tncm91bmQ6ICMwYjdkZGE7XHJcbn1cclxuIiwiLmJ0biB7XG4gIGJvcmRlcjogbm9uZTtcbiAgY29sb3I6IHdoaXRlO1xuICBwYWRkaW5nOiAxNHB4IDY2cHg7XG4gIGN1cnNvcjogcG9pbnRlcjtcbn1cblxuLm9rIHtcbiAgYmFja2dyb3VuZC1jb2xvcjogIzIxOTZmMztcbn1cblxuLm9rOmhvdmVyIHtcbiAgYmFja2dyb3VuZDogIzBiN2RkYTtcbn1cblxuLmJ0bjIge1xuICBib3JkZXI6IG5vbmU7XG4gIGNvbG9yOiB3aGl0ZTtcbiAgcGFkZGluZzogMjBweCAzNHB4O1xuICBmb250LXNpemU6IDE2cHg7XG4gIGN1cnNvcjogcG9pbnRlcjtcbn1cblxuLmd1ZXN0IHtcbiAgYmFja2dyb3VuZC1jb2xvcjogIzIxOTZmMztcbn1cblxuLmd1ZXN0OmhvdmVyIHtcbiAgYmFja2dyb3VuZDogIzBiN2RkYTtcbn0iXX0= */"];
exports.styles = styles;


/***/ }),

/***/ "./src/app/modules/busses/components/lines/lines.component.ts":
/*!********************************************************************!*\
  !*** ./src/app/modules/busses/components/lines/lines.component.ts ***!
  \********************************************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

Object.defineProperty(exports, "__esModule", { value: true });
const core_1 = __webpack_require__(/*! @angular/core */ "@angular/core");
class LinesComponent {
    constructor() {
        this.lines = [1, 4, 6, 7, 9, 10, 11, 12, 15, 16, 17, 18, 20, 21, 22, 24, 25, 26, 27, 29, 36, 37, 44, 66, 93, 99, 113, 116, 222];
    }
    ngOnInit() { }
}
exports.LinesComponent = LinesComponent;


/***/ }),

/***/ "./src/app/modules/busses/services/busses.service.ts":
/*!***********************************************************!*\
  !*** ./src/app/modules/busses/services/busses.service.ts ***!
  \***********************************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

Object.defineProperty(exports, "__esModule", { value: true });
class BussesService {
    constructor(httpClient, constants) {
        this.httpClient = httpClient;
        this.constants = constants;
    }
    createBus(createBusDTO) {
        return this.httpClient.post(`${this.constants.apiURL}/Busses`, createBusDTO);
    }
    deleteBus(id) {
        return this.httpClient.request('delete', `${this.constants.apiURL}/Busses`, { body: { id } });
    }
    getBusses(lineId) {
        return this.httpClient.post(`${this.constants.apiURL}/Busses/all`, { lineId });
    }
    getBus(id) {
        return this.httpClient.get(`${this.constants.apiURL}/Busses/${id}`);
    }
    createBussesBusStops(createBussesBusStopsDTO) {
        return this.httpClient.post(`${this.constants.apiURL}/BussesBusStops`, createBussesBusStopsDTO);
    }
    deleteBussesBusStops(id) {
        return this.httpClient.request('delete', `${this.constants.apiURL}/BussesBusStops`, { body: { id } });
    }
    getBussesBusStopsByBusId(busId) {
        return this.httpClient.post(`${this.constants.apiURL}/BussesBusStops/busStops`, { busId });
    }
    getBussesBusStopsByBusStopId(busStopId) {
        return this.httpClient.post(`${this.constants.apiURL}/BussesBusStops/busses`, { busStopId });
    }
    createBusStop(createBusStopDTO) {
        return this.httpClient.post(`${this.constants.apiURL}/BusStops`, createBusStopDTO);
    }
    deleteBusStop(id) {
        return this.httpClient.request('delete', `${this.constants.apiURL}/BusStps`, { body: { id } });
    }
    getBusStops() {
        return this.httpClient.get(`${this.constants.apiURL}/BusStops`);
        ;
    }
    getBusStop(id) {
        return this.httpClient.get(`${this.constants.apiURL}/BusStops/${id}`);
    }
    createLine(createLineDTO) {
        return this.httpClient.post(`${this.constants.apiURL}/Lines`, createLineDTO);
    }
    deleteLine(id) {
        return this.httpClient.request('delete', `${this.constants.apiURL}/Lines`, { body: { id } });
    }
    getLines() {
        return this.httpClient.get(`${this.constants.apiURL}/Lines`);
        ;
    }
    getLine(id) {
        return this.httpClient.get(`${this.constants.apiURL}/Lines/${id}`);
    }
    createUsersBusses(createUsersBussesDTO) {
        return this.httpClient.post(`${this.constants.apiURL}/UsersBusses`, createUsersBussesDTO);
    }
    deleteUsersBusses(id) {
        return this.httpClient.request('delete', `${this.constants.apiURL}/UsersBusses`, { body: { id } });
    }
}
exports.BussesService = BussesService;


/***/ }),

/***/ "./src/app/modules/shared/config/constants.config.ts":
/*!***********************************************************!*\
  !*** ./src/app/modules/shared/config/constants.config.ts ***!
  \***********************************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

Object.defineProperty(exports, "__esModule", { value: true });
class Constants {
    constructor() {
        this.apiURL = 'http://localhost:1337/api';
    }
}
exports.Constants = Constants;


/***/ }),

/***/ "./src/app/modules/shared/guards/auth.guard.ts":
/*!*****************************************************!*\
  !*** ./src/app/modules/shared/guards/auth.guard.ts ***!
  \*****************************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

Object.defineProperty(exports, "__esModule", { value: true });
const constants_1 = __webpack_require__(/*! ../../../constants */ "./src/app/constants.ts");
class AuthGuard {
    constructor(router, storageService) {
        this.router = router;
        this.storageService = storageService;
    }
    canActivate(route, state) {
        if (!this.storageService.getItem(constants_1.JWT_KEY)) {
            this.router.navigate(['/login']);
            return false;
        }
        return true;
    }
}
exports.AuthGuard = AuthGuard;


/***/ }),

/***/ "./src/app/modules/shared/guards/unauth.guard.ts":
/*!*******************************************************!*\
  !*** ./src/app/modules/shared/guards/unauth.guard.ts ***!
  \*******************************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

Object.defineProperty(exports, "__esModule", { value: true });
const constants_1 = __webpack_require__(/*! ../../../constants */ "./src/app/constants.ts");
class UnauthGuard {
    constructor(router, storageService) {
        this.router = router;
        this.storageService = storageService;
    }
    canActivate(route, state) {
        if (this.storageService.getItem(constants_1.JWT_KEY)) {
            this.router.navigate(['/busses']);
            return false;
        }
        return true;
    }
}
exports.UnauthGuard = UnauthGuard;


/***/ }),

/***/ "./src/app/modules/shared/interceptors/jwt.interceptor.ts":
/*!****************************************************************!*\
  !*** ./src/app/modules/shared/interceptors/jwt.interceptor.ts ***!
  \****************************************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

Object.defineProperty(exports, "__esModule", { value: true });
const constants_1 = __webpack_require__(/*! ../../../constants */ "./src/app/constants.ts");
class JwtInterceptor {
    constructor(storageService) {
        this.storageService = storageService;
    }
    intercept(request, next) {
        let headers = request.headers.set('Content-Type', 'application/json');
        const jwt = this.storageService.getItem(constants_1.JWT_KEY);
        if (jwt) {
            headers = headers.set('Authorization', `Bearer ${jwt}`);
        }
        const authReq = request.clone({ headers });
        return next.handle(authReq);
    }
}
exports.JwtInterceptor = JwtInterceptor;


/***/ }),

/***/ "./src/app/modules/shared/models/localStorage.model.ts":
/*!*************************************************************!*\
  !*** ./src/app/modules/shared/models/localStorage.model.ts ***!
  \*************************************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

Object.defineProperty(exports, "__esModule", { value: true });
class LocalStorage {
    constructor(runningInTheBrowser) {
        this.runningInTheBrowser = runningInTheBrowser;
    }
    getItem(key) {
        if (!this.runningInTheBrowser) {
            return;
        }
        return localStorage.getItem(key);
    }
    setItem(key, value) {
        if (!this.runningInTheBrowser) {
            return;
        }
        localStorage.setItem(key, value);
    }
    removeItem(key) {
        if (!this.runningInTheBrowser) {
            return;
        }
        localStorage.removeItem(key);
    }
}
exports.LocalStorage = LocalStorage;


/***/ }),

/***/ "./src/app/modules/shared/providers/constants.providers.ts":
/*!*****************************************************************!*\
  !*** ./src/app/modules/shared/providers/constants.providers.ts ***!
  \*****************************************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

Object.defineProperty(exports, "__esModule", { value: true });
const constants_config_1 = __webpack_require__(/*! ../config/constants.config */ "./src/app/modules/shared/config/constants.config.ts");
exports.CONSTANTS_PROVIDERS = [
    {
        provide: constants_config_1.Constants,
        useClass: constants_config_1.Constants
    }
];


/***/ }),

/***/ "./src/app/modules/shared/services/storage.service.ts":
/*!************************************************************!*\
  !*** ./src/app/modules/shared/services/storage.service.ts ***!
  \************************************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

Object.defineProperty(exports, "__esModule", { value: true });
const localStorage_model_1 = __webpack_require__(/*! ../models/localStorage.model */ "./src/app/modules/shared/models/localStorage.model.ts");
const common_1 = __webpack_require__(/*! @angular/common */ "@angular/common");
class StorageService {
    constructor(platformId) {
        this.platformId = platformId;
        const runningInTheBrowser = common_1.isPlatformBrowser(platformId);
        this.storage = new localStorage_model_1.LocalStorage(runningInTheBrowser);
    }
    getItem(key) {
        return this.storage.getItem(key);
    }
    setItem(key, value) {
        return this.storage.setItem(key, value);
    }
    removeItem(key) {
        return this.storage.removeItem(key);
    }
}
exports.StorageService = StorageService;


/***/ }),

/***/ "./src/app/modules/shared/shared.module.ts":
/*!*************************************************!*\
  !*** ./src/app/modules/shared/shared.module.ts ***!
  \*************************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

Object.defineProperty(exports, "__esModule", { value: true });
const core_1 = __webpack_require__(/*! @angular/core */ "@angular/core");
const common_1 = __webpack_require__(/*! @angular/common */ "@angular/common");
const router_1 = __webpack_require__(/*! @angular/router */ "@angular/router");
const forms_1 = __webpack_require__(/*! @angular/forms */ "@angular/forms");
const auth_guard_1 = __webpack_require__(/*! ./guards/auth.guard */ "./src/app/modules/shared/guards/auth.guard.ts");
const constants_providers_1 = __webpack_require__(/*! ./providers/constants.providers */ "./src/app/modules/shared/providers/constants.providers.ts");
const http_1 = __webpack_require__(/*! @angular/common/http */ "@angular/common/http");
const jwt_interceptor_1 = __webpack_require__(/*! ./interceptors/jwt.interceptor */ "./src/app/modules/shared/interceptors/jwt.interceptor.ts");
const unauth_guard_1 = __webpack_require__(/*! ./guards/unauth.guard */ "./src/app/modules/shared/guards/unauth.guard.ts");
const storage_service_1 = __webpack_require__(/*! ./services/storage.service */ "./src/app/modules/shared/services/storage.service.ts");
const MODULES = [common_1.CommonModule, router_1.RouterModule, forms_1.FormsModule, forms_1.ReactiveFormsModule];
const GUARDS = [auth_guard_1.AuthGuard, unauth_guard_1.UnauthGuard];
const PROVIDERS = [...constants_providers_1.CONSTANTS_PROVIDERS];
const SERVICES = [storage_service_1.StorageService];
const INTERCEPTORS = [
    {
        provide: http_1.HTTP_INTERCEPTORS,
        useClass: jwt_interceptor_1.JwtInterceptor,
        multi: true
    }
];
class SharedModule {
    static forRoot() {
        return {
            ngModule: SharedModule,
            providers: [
                ...GUARDS,
                ...PROVIDERS,
                ...INTERCEPTORS,
                ...SERVICES
            ]
        };
    }
}
exports.SharedModule = SharedModule;


/***/ }),

/***/ "./src/main.server.ts":
/*!****************************!*\
  !*** ./src/main.server.ts ***!
  \****************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

Object.defineProperty(exports, "__esModule", { value: true });
var app_server_module_ngfactory_1 = __webpack_require__(/*! ./app/app.server.module.ngfactory */ "./src/app/app.server.module.ngfactory.js");
exports.AppServerModuleNgFactory = app_server_module_ngfactory_1.AppServerModuleNgFactory;
var app_server_module_1 = __webpack_require__(/*! ./app/app.server.module */ "./src/app/app.server.module.ts");
exports.AppServerModule = app_server_module_1.AppServerModule;
exports.LAZY_MODULE_MAP = {};


/***/ }),

/***/ 0:
/*!**********************************!*\
  !*** multi ./src/main.server.ts ***!
  \**********************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

module.exports = __webpack_require__(/*! D:\ANGULAR\Busses\busses-fe\src\main.server.ts */"./src/main.server.ts");


/***/ }),

/***/ "@angular/animations":
/*!**************************************!*\
  !*** external "@angular/animations" ***!
  \**************************************/
/*! no static exports found */
/***/ (function(module, exports) {

module.exports = require("@angular/animations");

/***/ }),

/***/ "@angular/animations/browser":
/*!**********************************************!*\
  !*** external "@angular/animations/browser" ***!
  \**********************************************/
/*! no static exports found */
/***/ (function(module, exports) {

module.exports = require("@angular/animations/browser");

/***/ }),

/***/ "@angular/common":
/*!**********************************!*\
  !*** external "@angular/common" ***!
  \**********************************/
/*! no static exports found */
/***/ (function(module, exports) {

module.exports = require("@angular/common");

/***/ }),

/***/ "@angular/common/http":
/*!***************************************!*\
  !*** external "@angular/common/http" ***!
  \***************************************/
/*! no static exports found */
/***/ (function(module, exports) {

module.exports = require("@angular/common/http");

/***/ }),

/***/ "@angular/core":
/*!********************************!*\
  !*** external "@angular/core" ***!
  \********************************/
/*! no static exports found */
/***/ (function(module, exports) {

module.exports = require("@angular/core");

/***/ }),

/***/ "@angular/forms":
/*!*********************************!*\
  !*** external "@angular/forms" ***!
  \*********************************/
/*! no static exports found */
/***/ (function(module, exports) {

module.exports = require("@angular/forms");

/***/ }),

/***/ "@angular/platform-browser":
/*!********************************************!*\
  !*** external "@angular/platform-browser" ***!
  \********************************************/
/*! no static exports found */
/***/ (function(module, exports) {

module.exports = require("@angular/platform-browser");

/***/ }),

/***/ "@angular/platform-browser/animations":
/*!*******************************************************!*\
  !*** external "@angular/platform-browser/animations" ***!
  \*******************************************************/
/*! no static exports found */
/***/ (function(module, exports) {

module.exports = require("@angular/platform-browser/animations");

/***/ }),

/***/ "@angular/platform-server":
/*!*******************************************!*\
  !*** external "@angular/platform-server" ***!
  \*******************************************/
/*! no static exports found */
/***/ (function(module, exports) {

module.exports = require("@angular/platform-server");

/***/ }),

/***/ "@angular/router":
/*!**********************************!*\
  !*** external "@angular/router" ***!
  \**********************************/
/*! no static exports found */
/***/ (function(module, exports) {

module.exports = require("@angular/router");

/***/ }),

/***/ "@nguniversal/module-map-ngfactory-loader":
/*!***********************************************************!*\
  !*** external "@nguniversal/module-map-ngfactory-loader" ***!
  \***********************************************************/
/*! no static exports found */
/***/ (function(module, exports) {

module.exports = require("@nguniversal/module-map-ngfactory-loader");

/***/ }),

/***/ "rxjs/operators":
/*!*********************************!*\
  !*** external "rxjs/operators" ***!
  \*********************************/
/*! no static exports found */
/***/ (function(module, exports) {

module.exports = require("rxjs/operators");

/***/ })

/******/ })));
//# sourceMappingURL=main.js.map